/*
 *   IMPORTS
 ***************************************************************************************************/
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { findWorkspaceRoot, type Workspace } from '../core/workspace.js'
import { MANIFEST_FILE, parseManifest } from '../core/config.js'
import { appDependencies, PNPM_VERSION, rootDevDependencies } from '../core/versions.js'
import {
	appConfigFiles,
	helperFile,
	hostWiringFiles,
	NODE_RANGE,
	WORKSPACE_SCRIPTS,
	workspaceFiles,
} from '../core/generators.js'
import * as p from '@clack/prompts'
import { dependencyHome, editJsonFile, type PackageJsonShape } from '../core/packages.js'
import { Provenance } from '../core/provenance.js'
import { resolveRanges, type RangeInfo } from '../core/ranges.js'
import { formatFiles } from '../core/format.js'
import { CliError } from '../util/errors.js'
import { log } from '../util/logger.js'
import { isUpgrade } from '../util/semver.js'

/*
 *   TYPES
 ***************************************************************************************************/
export interface UpgradeOptions {
	dryRun?: boolean
	pin?: boolean
	force?: boolean
}

interface UpgradeContext {
	ws: Workspace
	writer: ChangeWriter
	/** Use spool's own ranges verbatim instead of what the workspace asks for. */
	pin: boolean
	ranges: Map<string, RangeInfo>
}

/** Regenerating a config that lost this marker would destroy user edits. */
const GENERATED_MARKER = 'Generated by spool'

const shouldSet = (from: string | undefined, to: string, pin: boolean): boolean =>
	pin ? from !== to : isUpgrade(from, to)

const targetRange = (ctx: UpgradeContext, dep: string, ours: string): string =>
	ctx.pin ? ours : (ctx.ranges.get(dep)?.target ?? ours)

/*
 *   UPGRADE
 ***************************************************************************************************/
export async function upgrade(opts: UpgradeOptions): Promise<void> {
	const root = findWorkspaceRoot()
	const provenance = root === null ? null : Provenance.load(root)
	const writer = new ChangeWriter(opts.dryRun ?? false, provenance, opts.force ?? false)
	const ws = await loadForUpgrade(writer)
	const ctx: UpgradeContext = { ws, writer, pin: opts.pin ?? false, ranges: resolveRanges(ws) }

	await upgradeRoot(ctx)
	for (const [name, app] of Object.entries(ws.manifest.apps)) {
		const dir = join(ws.root, app.path)

		if (!existsSync(dir)) {
			log.warn(`${name}: folder "${app.path}" is missing, skipping. Run \`spool doctor\`.`)
			continue
		}

		const generated = await formatFiles(
			appConfigFiles(name, app, ws.manifest.addons.includes('sentry'))
		)

		await writer.replaceGenerated(dir, 'vite.config.ts', generated['vite.config.ts']!, name)
		if (app.type === 'remote') {
			await writer.add(dir, 'public/_headers', generated['public/_headers']!, name)
		}

		const typings = await formatFiles(hostWiringFiles(ws.manifest, app))
		for (const [rel, content] of Object.entries(typings)) {
			await writer.replace(dir, rel, content, name)
		}

		await upgradeAppPackage(ctx, name, dir)
	}

	if (!opts.dryRun) await provenance?.save()
	writer.summarize(ws)
}

async function loadForUpgrade(writer: ChangeWriter): Promise<Workspace> {
	const root = findWorkspaceRoot()
	if (!root) {
		throw new CliError(
			`No ${MANIFEST_FILE} found. Run \`spool create\` first, or cd into a spool workspace.`
		)
	}

	let raw: unknown
	await writer.editJson(root, MANIFEST_FILE, 'workspace', manifest => {
		raw = manifest
		if (manifest.bundler !== 'rspack') return []

		delete manifest.bundler
		return ['removed unsupported bundler "rspack"']
	})

	return { root, manifestPath: join(root, MANIFEST_FILE), manifest: parseManifest(raw) }
}

async function upgradeRoot(ctx: UpgradeContext): Promise<void> {
	const { ws, writer, pin } = ctx
	const helper = await formatFiles(helperFile())

	for (const [rel, content] of Object.entries(helper)) {
		await writer.replaceGenerated(ws.root, rel, content, 'workspace')
	}

	// Missing root files come from the same generator `create` uses, so an
	// upgraded workspace and a fresh scaffold never drift apart.
	const rootFiles = workspaceFiles(ws.manifest)
	const rootConfigs = await formatFiles({
		'tsconfig.json': rootFiles['tsconfig.json']!,
		'.prettierignore': rootFiles['.prettierignore']!,
	})

	for (const [rel, content] of Object.entries(rootConfigs)) {
		await writer.add(ws.root, rel, content, 'workspace')
	}

	await writer.editJson(ws.root, 'package.json', 'workspace', pkg => {
		const changes: string[] = []
		if (shouldSet(pkg.engines?.node, NODE_RANGE, pin)) {
			pkg.engines = { ...pkg.engines, node: NODE_RANGE }
			changes.push(`engines.node -> ${NODE_RANGE}`)
		}

		// Only missing scripts are added; edited ones belong to the user.
		pkg.scripts ??= {}
		for (const [script, command] of Object.entries(WORKSPACE_SCRIPTS)) {
			if (pkg.scripts[script] === undefined) {
				pkg.scripts[script] = command
				changes.push(`scripts.${script} added`)
			}
		}

		if (
			ws.manifest.packageManager === 'pnpm' &&
			pkg.packageManager !== `pnpm@${PNPM_VERSION}`
		) {
			pkg.packageManager = `pnpm@${PNPM_VERSION}`
			changes.push(`packageManager -> pnpm@${PNPM_VERSION}`)
		}

		pkg.devDependencies ??= {}
		const expected = rootDevDependencies()
		for (const [dep, ours] of Object.entries(expected)) {
			const range = targetRange(ctx, dep, ours)
			const current = pkg.devDependencies[dep]

			if (shouldSet(current, range, pin)) {
				changes.push(`${dep} ${current ?? 'added'} -> ${range}`)
				pkg.devDependencies[dep] = range
			} else if (current !== range) writer.noteKept()
		}

		return changes
	})
}

async function upgradeAppPackage(ctx: UpgradeContext, name: string, dir: string): Promise<void> {
	const { ws, writer, pin } = ctx
	const app = ws.manifest.apps[name]!
	const expected = appDependencies(ws.manifest, app)

	await writer.editJson(dir, 'package.json', name, pkg => {
		const changes: string[] = []
		pkg.dependencies ??= {}
		pkg.devDependencies ??= {}

		// Deps the framework no longer implies are left alone; the user may
		// use them directly. Only expected entries are added or updated.
		for (const [section, expectedDeps] of [
			['dependencies', expected.dependencies],
			['devDependencies', expected.devDependencies],
		] as const) {
			for (const [dep, ours] of Object.entries(expectedDeps)) {
				const range = targetRange(ctx, dep, ours)
				const home = dependencyHome(pkg, dep, section)

				if (shouldSet(home[dep], range, pin)) {
					changes.push(`${dep} ${home[dep] ?? 'added'} -> ${range}`)
					home[dep] = range
				} else if (home[dep] !== range) writer.noteKept()
			}
		}

		if (shouldSet(pkg.engines?.node, NODE_RANGE, pin)) {
			pkg.engines = { ...pkg.engines, node: NODE_RANGE }
			changes.push(`engines.node -> ${NODE_RANGE}`)
		}

		return changes
	})
}

/*
 *   CHANGE WRITER
 ***************************************************************************************************/
class ChangeWriter {
	public changed = 0
	private kept = 0
	private skipped = 0
	/** Set once the user answers "every file" either way. */
	private overwriteAll: boolean | null = null

	constructor(
		private readonly dryRun: boolean,
		private readonly provenance: Provenance | null,
		private readonly force: boolean
	) { }

	private get verb(): string {
		return this.dryRun ? 'would update' : 'updated'
	}

	async replace(dir: string, rel: string, content: string, label: string): Promise<void> {
		const target = join(dir, rel)
		const existing = existsSync(target) ? await readFile(target, 'utf8') : null
		if (existing === content) return

		this.changed++
		log.step(`${label}: ${this.verb} ${rel}`)
		if (!this.dryRun) {
			await mkdir(dirname(target), { recursive: true })
			await writeFile(target, content, 'utf8')
			this.provenance?.record(dir, rel, content)
		}
	}

	/** Like replace, but never overwrites a file the user has taken over. */
	async replaceGenerated(
		dir: string,
		rel: string,
		content: string,
		label: string
	): Promise<void> {
		const target = join(dir, rel)
		if (existsSync(target)) {
			const existing = await readFile(target, 'utf8')

			if (existing === content) {
				if (!this.dryRun) this.provenance?.record(dir, rel, content)
				return
			}

			if (!(await this.mayOverwrite(dir, rel, existing, label))) return
		}
		await this.replace(dir, rel, content, label)
	}

	private async mayOverwrite(
		dir: string,
		rel: string,
		existing: string,
		label: string
	): Promise<boolean> {
		switch (this.provenance?.ownership(dir, rel, existing) ?? 'unknown') {
			case 'ours':
				return true

			case 'edited':
				return this.confirmOverwrite(rel, label)

			case 'unknown':
				if (existing.includes(GENERATED_MARKER)) return true
				log.warn(
					`${label}: ${rel} was customized (no "${GENERATED_MARKER}" marker), leaving it alone. Delete it and rerun to regenerate.`
				)
				this.skipped++

				return false
		}
	}

	/** Never prompts without a tty: upgrade has to stay runnable in CI. */
	private async confirmOverwrite(rel: string, label: string): Promise<boolean> {
		if (this.force) return true

		if (this.dryRun) {
			log.step(`${label}: ${rel} has local changes; would ask before overwriting`)
			this.skipped++

			return false
		}

		if (this.overwriteAll !== null) {
			if (!this.overwriteAll) this.skipped++

			return this.overwriteAll
		}

		if (!process.stdin.isTTY) {
			log.warn(
				`${label}: ${rel} has local changes since spool wrote it, leaving it alone. Rerun with --force to overwrite.`
			)

			this.skipped++
			return false
		}

		const answer = await p.select({
			message: `${label}: ${rel} has local changes since spool wrote it.`,
			options: [
				{ value: 'keep', label: 'Keep my version' },
				{ value: 'overwrite', label: 'Overwrite it with the generated file' },
				{ value: 'keep-all', label: 'Keep mine, for every file' },
				{ value: 'overwrite-all', label: 'Overwrite every file' },
			],
			initialValue: 'keep',
		})

		if (p.isCancel(answer) || answer === 'keep') {
			this.skipped++
			return false
		}

		if (answer === 'overwrite') return true

		this.overwriteAll = answer === 'overwrite-all'
		if (!this.overwriteAll) this.skipped++

		return this.overwriteAll
	}

	async add(dir: string, rel: string, content: string, label: string): Promise<void> {
		if (existsSync(join(dir, rel))) return

		this.changed++
		log.step(`${label}: ${this.dryRun ? 'would add' : 'added'} ${rel}`)

		if (!this.dryRun) {
			await mkdir(dirname(join(dir, rel)), { recursive: true })
			await writeFile(join(dir, rel), content, 'utf8')

			this.provenance?.record(dir, rel, content)
		}
	}

	async editJson(
		dir: string,
		rel: string,
		label: string,
		edit: (pkg: PackageJsonShape) => string[]
	): Promise<void> {
		const changes = await editJsonFile(join(dir, rel), edit, { write: !this.dryRun })
		if (!changes.length) return

		this.changed++
		log.step(`${label}: ${this.verb} ${rel} (${changes.join(', ')})`)
	}

	noteKept(): void {
		this.kept++
	}

	summarize(ws: Workspace): void {
		if (this.skipped) {
			log.step(`left ${this.skipped} file(s) with local changes alone.`)
		}

		if (this.kept) {
			log.step(
				`left ${this.kept} dependency range(s) alone; spool cannot compare them to what it would write. Rerun with --pin to overwrite them.`
			)
		}

		if (!this.changed) {
			log.success('already up to date')
			return
		}

		if (this.dryRun) {
			log.success(`${this.changed} change(s) pending. Rerun without --dry-run to apply.`)
			return
		}

		log.success(`upgraded ${this.changed} file(s)`)
		log.step(
			`Review the changes with git, run \`${ws.manifest.packageManager} install\`, then \`spool doctor\`.`
		)
	}
}
