/*
 *   IMPORTS
 ***************************************************************************************************/
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { findWorkspaceRoot, type Workspace } from '../core/workspace.js'
import { MANIFEST_FILE, parseManifest } from '../core/config.js'
import { appDependencies, CLI_VERSION, PNPM_VERSION, TOOLCHAIN } from '../core/versions.js'
import {
	appConfigFiles,
	helperFile,
	hostWiringFiles,
	NODE_RANGE,
	WORKSPACE_SCRIPTS,
	workspaceFiles,
} from '../core/generators.js'
import { formatFiles } from '../core/format.js'
import { CliError } from '../util/errors.js'
import { log } from '../util/logger.js'

/*
 *   TYPES
 ***************************************************************************************************/
export interface UpgradeOptions {
	dryRun?: boolean
}

/** Regenerating a config that lost this marker would destroy user edits. */
const GENERATED_MARKER = 'Generated by spool'

/*
 *   UPGRADE
 ***************************************************************************************************/
export async function upgrade(opts: UpgradeOptions): Promise<void> {
	const writer = new ChangeWriter(opts.dryRun ?? false)
	const ws = await loadForUpgrade(writer)

	await upgradeRoot(ws, writer)
	for (const [name, app] of Object.entries(ws.manifest.apps)) {
		const dir = join(ws.root, app.path)
		if (!existsSync(dir)) {
			log.warn(`${name}: folder "${app.path}" is missing, skipping. Run \`spool doctor\`.`)
			continue
		}

		const generated = await formatFiles(appConfigFiles(name, app))
		await writer.replaceGenerated(dir, 'vite.config.ts', generated['vite.config.ts']!, name)
		if (app.type === 'remote') {
			await writer.add(dir, 'public/_headers', generated['public/_headers']!, name)
		}
		const typings = await formatFiles(hostWiringFiles(ws.manifest, app))
		for (const [rel, content] of Object.entries(typings)) {
			await writer.replace(dir, rel, content, name)
		}

		await upgradeAppPackage(ws, name, dir, writer)
	}

	writer.summarize(ws)
}

async function loadForUpgrade(writer: ChangeWriter): Promise<Workspace> {
	const root = findWorkspaceRoot()
	if (!root) {
		throw new CliError(
			`No ${MANIFEST_FILE} found. Run \`spool create\` first, or cd into a spool workspace.`
		)
	}

	let raw: unknown
	await writer.editJson(root, MANIFEST_FILE, 'workspace', manifest => {
		raw = manifest
		if (manifest.bundler !== 'rspack') return []
		delete manifest.bundler
		return ['removed unsupported bundler "rspack"']
	})
	return { root, manifestPath: join(root, MANIFEST_FILE), manifest: parseManifest(raw) }
}

async function upgradeRoot(ws: Workspace, writer: ChangeWriter): Promise<void> {
	const helper = await formatFiles(helperFile())
	for (const [rel, content] of Object.entries(helper)) {
		await writer.replaceGenerated(ws.root, rel, content, 'workspace')
	}

	// Missing root files come from the same generator `create` uses, so an
	// upgraded workspace and a fresh scaffold never drift apart.
	const rootFiles = workspaceFiles(ws.manifest)
	const rootConfigs = await formatFiles({
		'tsconfig.json': rootFiles['tsconfig.json']!,
		'.prettierignore': rootFiles['.prettierignore']!,
	})
	for (const [rel, content] of Object.entries(rootConfigs)) {
		await writer.add(ws.root, rel, content, 'workspace')
	}

	await writer.editJson(ws.root, 'package.json', 'workspace', pkg => {
		const changes: string[] = []
		if (pkg.engines?.node !== NODE_RANGE) {
			pkg.engines = { ...pkg.engines, node: NODE_RANGE }
			changes.push(`engines.node -> ${NODE_RANGE}`)
		}
		// Only missing scripts are added; edited ones belong to the user.
		pkg.scripts ??= {}
		for (const [script, command] of Object.entries(WORKSPACE_SCRIPTS)) {
			if (pkg.scripts[script] === undefined) {
				pkg.scripts[script] = command
				changes.push(`scripts.${script} added`)
			}
		}
		if (
			ws.manifest.packageManager === 'pnpm' &&
			pkg.packageManager !== `pnpm@${PNPM_VERSION}`
		) {
			pkg.packageManager = `pnpm@${PNPM_VERSION}`
			changes.push(`packageManager -> pnpm@${PNPM_VERSION}`)
		}
		pkg.devDependencies ??= {}
		const expected: Record<string, string> = {
			typescript: TOOLCHAIN.typescript,
			'@types/node': TOOLCHAIN['@types/node'],
			'@bkincz/spool': `^${CLI_VERSION}`,
		}
		for (const [dep, range] of Object.entries(expected)) {
			if (pkg.devDependencies[dep] !== range) {
				changes.push(`${dep} ${pkg.devDependencies[dep] ?? 'added'} -> ${range}`)
				pkg.devDependencies[dep] = range
			}
		}
		return changes
	})
}

async function upgradeAppPackage(
	ws: Workspace,
	name: string,
	dir: string,
	writer: ChangeWriter
): Promise<void> {
	const app = ws.manifest.apps[name]!
	const expected = appDependencies(ws.manifest, app)

	await writer.editJson(dir, 'package.json', name, pkg => {
		const changes: string[] = []
		pkg.dependencies ??= {}
		pkg.devDependencies ??= {}

		// Deps the framework no longer implies are left alone; the user may
		// use them directly. Only expected entries are added or updated.
		for (const [section, expectedDeps] of [
			['dependencies', expected.dependencies],
			['devDependencies', expected.devDependencies],
		] as const) {
			for (const [dep, range] of Object.entries(expectedDeps)) {
				const home = dependencyHome(pkg, dep, section)
				if (home[dep] !== range) {
					changes.push(`${dep} ${home[dep] ?? 'added'} -> ${range}`)
					home[dep] = range
				}
			}
		}

		if (pkg.engines?.node !== NODE_RANGE) {
			pkg.engines = { ...pkg.engines, node: NODE_RANGE }
			changes.push(`engines.node -> ${NODE_RANGE}`)
		}
		return changes
	})
}

/** A dep keeps the section it already lives in; new ones join `section`. */
export function dependencyHome(
	pkg: PackageJsonShape,
	dep: string,
	section: 'dependencies' | 'devDependencies'
): Record<string, string> {
	if (pkg.dependencies?.[dep] !== undefined) return pkg.dependencies
	if (pkg.devDependencies?.[dep] !== undefined) return pkg.devDependencies
	return pkg[section]!
}

/*
 *   CHANGE WRITER
 ***************************************************************************************************/
export interface PackageJsonShape {
	engines?: Record<string, string>
	packageManager?: string
	scripts?: Record<string, string>
	dependencies?: Record<string, string>
	devDependencies?: Record<string, string>
	[key: string]: unknown
}

/** Writes only real differences, so a second upgrade run reports nothing. */
class ChangeWriter {
	public changed = 0

	constructor(private readonly dryRun: boolean) {}

	private get verb(): string {
		return this.dryRun ? 'would update' : 'updated'
	}

	async replace(dir: string, rel: string, content: string, label: string): Promise<void> {
		const target = join(dir, rel)
		const existing = existsSync(target) ? await readFile(target, 'utf8') : null
		if (existing === content) return

		this.changed++
		log.step(`${label}: ${this.verb} ${rel}`)
		if (!this.dryRun) {
			await mkdir(dirname(target), { recursive: true })
			await writeFile(target, content, 'utf8')
		}
	}

	/** Like replace, but never overwrites a file the user has taken over. */
	async replaceGenerated(
		dir: string,
		rel: string,
		content: string,
		label: string
	): Promise<void> {
		const target = join(dir, rel)
		if (existsSync(target)) {
			const existing = await readFile(target, 'utf8')
			if (existing === content) return
			if (!existing.includes(GENERATED_MARKER)) {
				log.warn(
					`${label}: ${rel} was customized (no "${GENERATED_MARKER}" marker), leaving it alone. Delete it and rerun to regenerate.`
				)
				return
			}
		}
		await this.replace(dir, rel, content, label)
	}

	async add(dir: string, rel: string, content: string, label: string): Promise<void> {
		if (existsSync(join(dir, rel))) return
		this.changed++
		log.step(`${label}: ${this.dryRun ? 'would add' : 'added'} ${rel}`)
		if (!this.dryRun) {
			await mkdir(dirname(join(dir, rel)), { recursive: true })
			await writeFile(join(dir, rel), content, 'utf8')
		}
	}

	async editJson(
		dir: string,
		rel: string,
		label: string,
		edit: (pkg: PackageJsonShape) => string[]
	): Promise<void> {
		const target = join(dir, rel)
		if (!existsSync(target)) return

		const pkg = JSON.parse(await readFile(target, 'utf8')) as PackageJsonShape
		const changes = edit(pkg)
		if (!changes.length) return

		this.changed++
		log.step(`${label}: ${this.verb} ${rel} (${changes.join(', ')})`)
		if (!this.dryRun) {
			const formatted = await formatFiles({ [rel]: `${JSON.stringify(pkg)}\n` })
			await writeFile(target, formatted[rel]!, 'utf8')
		}
	}

	summarize(ws: Workspace): void {
		if (!this.changed) {
			log.success('already up to date')
			return
		}
		if (this.dryRun) {
			log.success(`${this.changed} change(s) pending. Rerun without --dry-run to apply.`)
			return
		}
		log.success(`upgraded ${this.changed} file(s)`)
		log.step(
			`Review the changes with git, run \`${ws.manifest.packageManager} install\`, then \`spool doctor\`.`
		)
	}
}
