/*
 *   IMPORTS
 ***************************************************************************************************/
import { HELPER_FILE, WORKSPACE_FILE } from '../config.js'
import type { FileMap } from '../filemap.js'

/*
 *   ROOT HELPERS
 ***************************************************************************************************/
export function helperFiles(): FileMap {
	return {
		[HELPER_FILE]: spoolViteHelper(),
		[WORKSPACE_FILE]: spoolWorkspaceHelper(),
	}
}

function spoolWorkspaceHelper(): string {
	return `/*
 * Generated by spool. Reads spool.json when it is imported, so the app list
 * is never stale. Edit spool.json, not this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type SpoolFramework = "react" | "svelte" | "vue";

export interface WorkspaceApp {
  name: string;
  type: "host" | "remote";
  framework: SpoolFramework;
  port: number;
  /** Absolute path to the app folder. */
  dir: string;
  /** Absolute path to the app\u2019s src folder. */
  src: string;
  /** Remotes a host consumes. Empty for a remote. */
  remotes: string[];
  /** Modules a remote exposes. Empty for a host. */
  exposes: Record<string, string>;
}

interface RawApp {
  type: "host" | "remote";
  framework?: SpoolFramework;
  path: string;
  port: number;
  remotes?: string[];
  exposes?: Record<string, string>;
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.workspace: no spool.json found above " + from);
    dir = parent;
  }
}

const manifestPath = findManifest(import.meta.dirname);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
  name: string;
  shared?: string[];
  addons?: string[];
  apps: Record<string, RawApp>;
};

/** Absolute path to the workspace root, where spool.json lives. */
export const root: string = dirname(manifestPath);

export const workspaceName: string = manifest.name;
export const shared: string[] = manifest.shared ?? [];
export const addons: string[] = manifest.addons ?? [];

export const apps: WorkspaceApp[] = Object.entries(manifest.apps).map(([name, entry]) => ({
  name,
  type: entry.type,
  framework: entry.framework ?? "react",
  port: entry.port,
  dir: join(root, entry.path),
  src: join(root, entry.path, "src"),
  remotes: entry.remotes ?? [],
  exposes: entry.exposes ?? {},
}));

export const hosts: WorkspaceApp[] = apps.filter(entry => entry.type === "host");
export const remotes: WorkspaceApp[] = apps.filter(entry => entry.type === "remote");

/** Every app\u2019s src folder, for sweeps that should cover the whole workspace. */
export const srcDirs: string[] = apps.map(entry => entry.src);

export function app(name: string): WorkspaceApp {
  const found = apps.find(entry => entry.name === name);
  if (!found) throw new Error(\`spool.workspace: no app named "\${name}" in spool.json\`);
  return found;
}
`
}

function spoolViteHelper(): string {
	return `/**
 * Generated by spool. Reads spool.json when Vite loads the config and derives
 * the app's dev server and Module Federation settings. Edit spool.json, not
 * this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export interface SpoolAppEntry {
  type: "host" | "remote";
  path: string;
  port: number;
  url?: string;
  urls?: Record<string, string>;
  remotes?: string[];
  exposes?: Record<string, string>;
}

export interface SpoolProxyEntry {
  target: string;
  changeOrigin?: boolean;
  secure?: boolean;
  ws?: boolean;
}

export interface SpoolServerConfig {
  proxy?: Record<string, string | SpoolProxyEntry>;
  headers?: Record<string, string>;
  host?: boolean | string;
  cors?: boolean;
}

export type SpoolShareStrategy = "version-first" | "loaded-first";

export interface SpoolManifest {
  name: string;
  shared?: string[];
  shareStrategy?: SpoolShareStrategy;
  server?: SpoolServerConfig;
  apps: Record<string, SpoolAppEntry>;
}

export interface SpoolAppConfig {
  /** Vite server/preview settings for this app. */
  server: SpoolServerConfig & { port: number; strictPort: boolean };
  /** Options for the federation() plugin from @module-federation/vite. */
  federation: {
    name: string;
    filename?: string;
    manifest?: boolean;
    remotes?: Record<string, string>;
    exposes?: Record<string, string>;
    shared: Record<string, { singleton: boolean }>;
    shareStrategy: SpoolShareStrategy;
    dts: false;
  };
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.vite: no spool.json found above " + from);
    dir = parent;
  }
}

/**
 * Remote lookup order. The SPOOL_REMOTE_<NAME> env var, then the remote's url
 * for the current SPOOL_ENV, then its plain url, then the local dev server.
 * Only builds read the deployed urls, so dev always stays on localhost.
 */
function remoteUrl(name: string, app: SpoolAppEntry, command: SpoolCommand): string {
  const envKey = "SPOOL_REMOTE_" + name.toUpperCase().replace(/-/g, "_");
  const environment = process.env.SPOOL_ENV;
  const deployed =
    command === "build"
      ? (environment !== undefined ? app.urls?.[environment] : undefined) ?? app.url
      : undefined;
  return process.env[envKey] ?? deployed ?? "http://localhost:" + app.port + "/mf-manifest.json";
}

export type SpoolCommand = "build" | "serve";

/**
 * A shared dep the app has not declared in its own package.json is dropped, so
 * apps on different frameworks never share something they do not install.
 */
function declaredShared(dir: string, deps: string[]): string[] {
  if (!deps.length) return deps;
  let declared: Set<string>;
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    declared = new Set([
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]);
  } catch {
    // Better to share nothing than to share a dep the app never installed.
    console.warn(
      "[spool] could not read " + join(dir, "package.json") + "; sharing no deps for this app. Run spool doctor."
    );
    return [];
  }
  // "@scope/pkg/subpath" is declared through its package, "@scope/pkg".
  const packageName = (dep: string): string => {
    const parts = dep.split("/");
    return dep.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0]!;
  };
  return deps.filter(dep => declared.has(packageName(dep)));
}

const ENV_REF = /\\$\\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\\}/g;

/**
 * Expands \${VAR} and \${VAR:-fallback} through the manifest server block, so a
 * proxy target can differ per machine without anyone editing a vite config.
 */
function expandEnv<T>(value: T): T {
  if (typeof value === "string") {
    return value.replace(ENV_REF, (_, name: string, fallback?: string) =>
      process.env[name] ?? fallback ?? ""
    ) as T;
  }
  if (Array.isArray(value)) return value.map(expandEnv) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, inner]) => [key, expandEnv(inner)])
    ) as T;
  }
  return value;
}

export function spoolApp(
  name: string,
  from: string = process.cwd(),
  command: SpoolCommand = "serve"
): SpoolAppConfig {
  const manifest = JSON.parse(readFileSync(findManifest(from), "utf8")) as SpoolManifest;
  const app = manifest.apps[name];
  if (!app) throw new Error('spool.vite: no app named "' + name + '" in spool.json');

  // Every share is a singleton. Two copies of react break hooks, and workspace
  // packages carry module state that has to resolve to one copy.
  const shared = Object.fromEntries(
    declaredShared(from, manifest.shared ?? []).map(dep => [dep, { singleton: true }])
  );
  // loaded-first keeps share scope off the remotes, so one remote you cannot
  // reach does not hold the page blank while it retries.
  const shareStrategy: SpoolShareStrategy = manifest.shareStrategy ?? "loaded-first";
  // cors covers dev and preview, where a host fetches remotes cross-origin.
  // Manifest settings come last so a workspace can override them, but never the
  // port, which the app owns.
  const server = {
    port: app.port,
    strictPort: true,
    cors: true,
    ...expandEnv(manifest.server ?? {}),
  };

  // An app can do both. A remote that consumes another remote gets exposes and
  // a remotes map, which is how a feature app mounts a widget another one owns.
  const federation: SpoolAppConfig["federation"] = {
    name,
    // Remotes are typed through src/remotes.d.ts, so the DTS archive is
    // redundant and flaky to download. Every app writes a manifest because
    // spool build compares what they all resolved.
    manifest: true,
    shared,
    shareStrategy,
    dts: false,
  };

  if ((app.remotes ?? []).length) {
    const remotes: Record<string, string> = {};
    for (const remote of app.remotes ?? []) {
      const target = manifest.apps[remote];
      if (!target) {
        throw new Error('spool.vite: "' + name + '" references unknown remote "' + remote + '"');
      }
      remotes[remote] = remoteUrl(remote, target, command);
    }
    federation.remotes = remotes;
  }

  if (app.type === "remote") {
    federation.filename = "remoteEntry.js";
    federation.exposes = app.exposes ?? {};
  }

  return { server, federation };
}
`
}
