/*
 *   IMPORTS
 ***************************************************************************************************/
import { HELPER_FILE, WORKSPACE_FILE } from '../config.js'
import type { FileMap } from '../filemap.js'

/*
 *   ROOT HELPERS
 ***************************************************************************************************/
export function helperFiles(): FileMap {
	return {
		[HELPER_FILE]: spoolViteHelper(),
		[WORKSPACE_FILE]: spoolWorkspaceHelper(),
	}
}

function spoolWorkspaceHelper(): string {
	return `/*
 * Generated by spool. Reads spool.json when it is imported, so the app list
 * is never stale. Edit spool.json, not this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type SpoolFramework = "react" | "svelte" | "vue";

export interface WorkspaceApp {
  name: string;
  type: "host" | "remote";
  framework: SpoolFramework;
  port: number;
  /** Absolute path to the app folder. */
  dir: string;
  /** Absolute path to the app\u2019s src folder. */
  src: string;
  /** Remotes a host consumes; empty for a remote. */
  remotes: string[];
  /** Modules a remote exposes; empty for a host. */
  exposes: Record<string, string>;
}

interface RawApp {
  type: "host" | "remote";
  framework?: SpoolFramework;
  path: string;
  port: number;
  remotes?: string[];
  exposes?: Record<string, string>;
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.workspace: no spool.json found above " + from);
    dir = parent;
  }
}

const manifestPath = findManifest(import.meta.dirname);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
  name: string;
  shared?: string[];
  addons?: string[];
  apps: Record<string, RawApp>;
};

/** Absolute path to the workspace root, where spool.json lives. */
export const root: string = dirname(manifestPath);

export const workspaceName: string = manifest.name;
export const shared: string[] = manifest.shared ?? [];
export const addons: string[] = manifest.addons ?? [];

export const apps: WorkspaceApp[] = Object.entries(manifest.apps).map(([name, entry]) => ({
  name,
  type: entry.type,
  framework: entry.framework ?? "react",
  port: entry.port,
  dir: join(root, entry.path),
  src: join(root, entry.path, "src"),
  remotes: entry.remotes ?? [],
  exposes: entry.exposes ?? {},
}));

export const hosts: WorkspaceApp[] = apps.filter(entry => entry.type === "host");
export const remotes: WorkspaceApp[] = apps.filter(entry => entry.type === "remote");

/** Every app\u2019s src folder, for sweeps that should cover the whole workspace. */
export const srcDirs: string[] = apps.map(entry => entry.src);

export function app(name: string): WorkspaceApp {
  const found = apps.find(entry => entry.name === name);
  if (!found) throw new Error(\`spool.workspace: no app named "\${name}" in spool.json\`);
  return found;
}
`
}

function spoolViteHelper(): string {
	return `/**
 * Generated by spool. Reads spool.json when Vite loads the config and derives
 * the app's dev server and Module Federation settings. Edit spool.json, not
 * this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export interface SpoolAppEntry {
  type: "host" | "remote";
  path: string;
  port: number;
  url?: string;
  urls?: Record<string, string>;
  remotes?: string[];
  exposes?: Record<string, string>;
}

export interface SpoolProxyEntry {
  target: string;
  changeOrigin?: boolean;
  secure?: boolean;
  ws?: boolean;
}

export interface SpoolServerConfig {
  proxy?: Record<string, string | SpoolProxyEntry>;
  headers?: Record<string, string>;
  host?: boolean | string;
  cors?: boolean;
}

export interface SpoolManifest {
  name: string;
  shared?: string[];
  server?: SpoolServerConfig;
  apps: Record<string, SpoolAppEntry>;
}

export interface SpoolAppConfig {
  /** Vite server/preview settings for this app. */
  server: SpoolServerConfig & { port: number; strictPort: boolean };
  /** Options for the federation() plugin from @module-federation/vite. */
  federation: {
    name: string;
    filename?: string;
    manifest?: boolean;
    remotes?: Record<string, string>;
    exposes?: Record<string, string>;
    shared: Record<string, { singleton: boolean }>;
    dts: false;
  };
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.vite: no spool.json found above " + from);
    dir = parent;
  }
}

/**
 * Remote lookup order: SPOOL_REMOTE_<NAME> env var, the remote's url for the
 * SPOOL_ENV environment, its default "url" (production builds only, so dev
 * keeps hitting local servers), then the local dev server.
 */
function remoteUrl(name: string, app: SpoolAppEntry, command: SpoolCommand): string {
  const envKey = "SPOOL_REMOTE_" + name.toUpperCase().replace(/-/g, "_");
  const environment = process.env.SPOOL_ENV;
  const deployed =
    command === "build"
      ? (environment !== undefined ? app.urls?.[environment] : undefined) ?? app.url
      : undefined;
  return process.env[envKey] ?? deployed ?? "http://localhost:" + app.port + "/mf-manifest.json";
}

export type SpoolCommand = "build" | "serve";

/**
 * Shared deps the app does not declare in its own package.json are dropped,
 * so apps on different frameworks never share deps they don't install.
 */
function declaredShared(dir: string, deps: string[]): string[] {
  if (!deps.length) return deps;
  let declared: Set<string>;
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    declared = new Set([
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]);
  } catch {
    // Sharing nothing is safe (the app just bundles its own copies); sharing
    // deps the app may not have installed is not.
    console.warn(
      "[spool] could not read " + join(dir, "package.json") + "; sharing no deps for this app. Run spool doctor."
    );
    return [];
  }
  // "@scope/pkg/subpath" is declared through its package, "@scope/pkg".
  const packageName = (dep: string): string => {
    const parts = dep.split("/");
    return dep.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0]!;
  };
  return deps.filter(dep => declared.has(packageName(dep)));
}

const ENV_REF = /\\$\\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\\}/g;

/**
 * Expands \${VAR} and \${VAR:-fallback} through the manifest server block, so a
 * proxy target can differ per machine without anyone editing a vite config.
 */
function expandEnv<T>(value: T): T {
  if (typeof value === "string") {
    return value.replace(ENV_REF, (_, name: string, fallback?: string) =>
      process.env[name] ?? fallback ?? ""
    ) as T;
  }
  if (Array.isArray(value)) return value.map(expandEnv) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, inner]) => [key, expandEnv(inner)])
    ) as T;
  }
  return value;
}

export function spoolApp(
  name: string,
  from: string = process.cwd(),
  command: SpoolCommand = "serve"
): SpoolAppConfig {
  const manifest = JSON.parse(readFileSync(findManifest(from), "utf8")) as SpoolManifest;
  const app = manifest.apps[name];
  if (!app) throw new Error('spool.vite: no app named "' + name + '" in spool.json');

  // Singleton for every share: duplicated react breaks hooks, and workspace
  // packages often carry module-level state that must resolve to one copy.
  // Non-singleton workspace shares also hit a @module-federation/vite dev bug
  // where the generated loadShare module references __mfLocalShare without
  // importing it, crashing the app at boot.
  const shared = Object.fromEntries(
    declaredShared(from, manifest.shared ?? []).map(dep => [dep, { singleton: true }])
  );
  // cors covers dev and vite preview, where hosts fetch remotes cross-origin.
  // Manifest settings come last so a workspace can override the defaults,
  // but never the port, which the app entry owns.
  const server = {
    port: app.port,
    strictPort: true,
    cors: true,
    ...expandEnv(manifest.server ?? {}),
  };

  if (app.type === "host") {
    const remotes: Record<string, string> = {};
    for (const remote of app.remotes ?? []) {
      const target = manifest.apps[remote];
      if (!target) {
        throw new Error('spool.vite: host "' + name + '" references unknown remote "' + remote + '"');
      }
      remotes[remote] = remoteUrl(remote, target, command);
    }
    // dts:false: spool types remotes via src/remotes.d.ts, so the federation
    // DTS archive is redundant and its dev-server download is flaky.
    // manifest:true so a host records what it resolved for every shared dep,
    // which is what spool build compares across apps. Nothing loads it.
    return { server, federation: { name, remotes, shared, manifest: true, dts: false } };
  }

  return {
    server,
    federation: {
      name,
      filename: "remoteEntry.js",
      // Dev serves mf-manifest.json automatically; builds only emit it with
      // this flag, and hosts load remotes by their manifest URL.
      manifest: true,
      exposes: app.exposes ?? {},
      shared,
      dts: false,
    },
  };
}
`
}
