/*
 *   IMPORTS
 ***************************************************************************************************/
import { basename } from 'node:path'
import type { AppConfig, Framework, Manifest } from '../config.js'
import type { FileMap } from '../filemap.js'
import { remoteRefs, type RemoteRef } from './index.js'

/*
 *   TYPES
 ***************************************************************************************************/
/** Where a host's stubbed remotes live, relative to the app folder. */
const STUB_DIR = 'src/test'

const STUBS: Record<RemoteRef['contract'], string> = {
	component: `${STUB_DIR}/remote-component.tsx`,
	mount: `${STUB_DIR}/remote-mount.ts`,
}

/*
 *   ESLINT
 ***************************************************************************************************/
function frameworkLint(m: Manifest): { imports: string[]; extends: string[]; blocks: string[] } {
	const used = new Set(Object.values(m.apps).map(app => app.framework))
	const imports: string[] = []
	const extend: string[] = []
	const blocks: string[] = []

	if (used.has('react')) {
		imports.push('import reactHooks from "eslint-plugin-react-hooks";')
		extend.push('reactHooks.configs.flat.recommended')
	}
	if (used.has('svelte')) {
		imports.push('import svelte from "eslint-plugin-svelte";')
		blocks.push(`  {
    files: ["**/*.svelte"],
    extends: [svelte.configs.recommended],
    languageOptions: { parserOptions: { parser: tseslint.parser } },
  },`)
	}
	if (used.has('vue')) {
		imports.push('import vue from "eslint-plugin-vue";')
		blocks.push(`  {
    files: ["**/*.vue"],
    extends: [vue.configs["flat/recommended"]],
    languageOptions: { parserOptions: { parser: tseslint.parser } },
  },`)
	}
	return { imports, extends: extend, blocks }
}

export function eslintConfig(m: Manifest): string {
	const { imports, extends: extend, blocks } = frameworkLint(m)
	const shared = ['js.configs.recommended', 'tseslint.configs.recommended', ...extend]

	return `import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
${imports.join('\n')}${imports.length ? '\n' : ''}import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  globalIgnores(["**/dist", "**/coverage", "**/test-results", "**/.ladle"]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
${shared.map(entry => `      ${entry},`).join('\n')}
    ],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
${blocks.join('\n')}${blocks.length ? '\n' : ''}]);
`
}

/*
 *   VITEST
 ***************************************************************************************************/
/** The generated half: aliases that name every remote, so they go stale. */
export const ALIAS_FILE = 'src/test/remotes.alias.ts'

export function remoteAliasModule(m: Manifest, app: AppConfig): string {
	const refs = app.type === 'host' ? remoteRefs(m, app) : []
	const entries = refs.map(
		ref => `  "${ref.name}/App": resolvePath(here, "${basename(STUBS[ref.contract])}"),`
	)

	return `// Generated by spool. Regenerated whenever this app\u2019s remotes change.
import { resolve as resolvePath } from "node:path";

const here = import.meta.dirname;

// Federation cannot resolve a remote under vitest, so each one points at a
// stub you can edit. Add your own aliases in vitest.config.ts, not here.
export const remoteAliases: Record<string, string> = {
${entries.join('\n')}${entries.length ? '\n' : ''}};
`
}

export function vitestConfig(): string {
	return `import { defineConfig } from "vitest/config";
import { resolve as resolvePath } from "node:path";
import { remoteAliases } from "./src/test/remotes.alias";

// Yours to edit. Spool only regenerates src/test/remotes.alias.ts.
export default defineConfig({
  resolve: {
    alias: {
      "@": resolvePath(import.meta.dirname, "src"),
      ...remoteAliases,
    },
  },
  test: {
    environment: "happy-dom",
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      exclude: ["**/*.d.ts", "**/*.config.*", "**/*.test.*", "src/test/**"],
    },
  },
});
`
}

export function remoteStubs(m: Manifest, app: AppConfig): FileMap {
	if (app.type !== 'host') return {}

	const files: FileMap = {}
	for (const ref of remoteRefs(m, app)) {
		if (files[STUBS[ref.contract]]) continue
		files[STUBS[ref.contract]] = ref.contract === 'component' ? componentStub() : mountStub()
	}
	return files
}

function componentStub(): string {
	return `// Stands in for a federated remote during tests. Edit freely.
export default function RemoteStub() {
  return <div data-testid="remote-stub" />;
}
`
}

function mountStub(): string {
	return `// Stands in for a federated remote during tests. Edit freely.
export default function mount(el: HTMLElement): () => void {
  el.innerHTML = '<div data-testid="remote-stub"></div>';
  return () => {
    el.innerHTML = "";
  };
}
`
}

/*
 *   SCRIPTS
 ***************************************************************************************************/
export const TEST_SCRIPTS = {
	test: 'vitest',
	'test:run': 'vitest run',
	'test:coverage': 'vitest run --coverage',
}

export function typeCheckAll(m: Manifest): string {
	if (m.packageManager === 'npm') return 'npm run type-check --workspaces --if-present'
	if (m.packageManager === 'yarn') return 'yarn workspaces foreach -A run type-check'
	return 'pnpm -r type-check'
}

/*
 *   NOTES
 ***************************************************************************************************/
export function lintNotes(m: Manifest): string[] {
	return [`lint: \`${m.packageManager} run lint\` checks every app and package`]
}

export function testNotes(m: Manifest): string[] {
	return [
		`test: every app got a vitest.config.ts; run them all with \`${m.packageManager} run test\``,
		'test: hosts resolve their remotes to stubs in src/test, since federation cannot run under vitest',
	]
}

export function testFrameworks(m: Manifest): Framework[] {
	return [...new Set(Object.values(m.apps).map(app => app.framework))]
}
