/*
 *   IMPORTS
 ***************************************************************************************************/
import {
	HELPER_FILE,
	MANIFEST_FILE,
	WORKSPACE_FILE,
	type AppConfig,
	type Manifest,
} from '../config.js'
import type { FileMap } from '../filemap.js'

/*
 *   GITHUB WORKFLOWS
 ***************************************************************************************************/
const CHECK_STEPS: { script: string; label: string }[] = [
	{ script: 'doctor', label: 'Doctor' },
	{ script: 'type-check', label: 'Type check' },
	{ script: 'lint', label: 'Lint' },
	{ script: 'test', label: 'Test' },
	{ script: 'build', label: 'Build' },
]

/** Actions this template uses, pinned to a commit sha at generation time by `spool ci --pin`. */
export const PINNED_ACTIONS = {
	checkout: { owner: 'actions', repo: 'checkout', tag: 'v7' },
	setupNode: { owner: 'actions', repo: 'setup-node', tag: 'v6' },
	pnpmSetup: { owner: 'pnpm', repo: 'action-setup', tag: 'v6' },
} as const

export type ActionKey = keyof typeof PINNED_ACTIONS
export type ActionPins = Record<ActionKey, string>

/** A safe floor when the workspace names no node version anywhere. */
export const NODE_VERSION_FALLBACK = '22'

/** The literal fallback path filter when no workspace globs can be found. */
const PACKAGE_GLOB_FALLBACK = ['packages']

export interface CiContext {
	/** Passed to actions/setup-node; defaults to a safe fallback. */
	nodeVersion?: string
	/** Shared-package directories (not other apps) a deploy should also watch. */
	packageGlobs?: string[]
	/** Commit-pinned refs; anything missing falls back to an unpinned tag. */
	pins?: Partial<ActionPins>
}

function unpinnedRef(action: { owner: string; repo: string; tag: string }): string {
	return `${action.owner}/${action.repo}@${action.tag}`
}

function resolvePins(overrides: Partial<ActionPins> = {}): ActionPins {
	const defaults = Object.fromEntries(
		(Object.entries(PINNED_ACTIONS) as [ActionKey, (typeof PINNED_ACTIONS)[ActionKey]][]).map(
			([key, action]) => [key, unpinnedRef(action)]
		)
	) as ActionPins

	return { ...defaults, ...overrides }
}

export function ciWorkflows(
	m: Manifest,
	scripts: Record<string, string> = {},
	ctx: CiContext = {}
): FileMap {
	const nodeVersion = ctx.nodeVersion ?? NODE_VERSION_FALLBACK
	const packageGlobs = ctx.packageGlobs ?? PACKAGE_GLOB_FALLBACK
	const pins = resolvePins(ctx.pins)

	const files: FileMap = {
		'.github/workflows/ci.yml': checkWorkflow(m, scripts, nodeVersion, pins),
	}

	for (const [name, app] of Object.entries(m.apps)) {
		if (!app.deploy) continue

		files[`.github/workflows/deploy-${name}.yml`] = deployWorkflow(
			m,
			name,
			app,
			scripts,
			nodeVersion,
			packageGlobs,
			pins
		)
	}

	return files
}

/*
 *   SHARED STEPS
 ***************************************************************************************************/
function pnpmSetupStep(pm: Manifest['packageManager'], pins: ActionPins): string {
	return pm === 'pnpm' ? `\n            - uses: ${pins.pnpmSetup}\n` : ''
}

function setupSteps(pm: Manifest['packageManager'], nodeVersion: string, pins: ActionPins): string {
	return `            - uses: ${pins.checkout}
              with:
                  persist-credentials: false
${pnpmSetupStep(pm, pins)}
            - uses: ${pins.setupNode}
              with:
                  node-version: ${JSON.stringify(nodeVersion)}
                  cache: ${JSON.stringify(pm)}

            - name: Install
              run: ${INSTALL_COMMANDS[pm]}
`
}

function checkSteps(pm: Manifest['packageManager'], scripts: Record<string, string>): string {
	return CHECK_STEPS.filter(step => scripts[step.script] !== undefined)
		.map(
			step => `
            - name: ${step.label}
              run: ${pm} run ${step.script}`
		)
		.join('\n')
}

/*
 *   CHECK WORKFLOW
 ***************************************************************************************************/
function checkWorkflow(
	m: Manifest,
	scripts: Record<string, string>,
	nodeVersion: string,
	pins: ActionPins
): string {
	const pm = m.packageManager

	return `# Generated by spool ci. Checks the whole workspace; the deploy-*.yml
# workflows ship individual apps. Spool cannot know your default branch, so
# change the branches list below if it is not main.
name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

permissions:
    contents: read

concurrency:
    group: \${{ github.workflow }}-\${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
${setupSteps(pm, nodeVersion, pins)}${checkSteps(pm, scripts)}
`
}

/*
 *   DEPLOY WORKFLOW
 ***************************************************************************************************/
function sharedPackageGlobs(m: Manifest, packageGlobs: string[]): string[] {
	const appPaths = new Set(Object.values(m.apps).map(app => app.path))
	const shared = packageGlobs.filter(dir => !appPaths.has(dir))
	return (shared.length ? shared : PACKAGE_GLOB_FALLBACK).map(dir => `${dir}/**`)
}

function pathFilters(m: Manifest, app: AppConfig, packageGlobs: string[]): string {
	const pm = m.packageManager
	const entries = [
		`${app.path}/**`,
		...sharedPackageGlobs(m, packageGlobs),
		MANIFEST_FILE,
		HELPER_FILE,
		WORKSPACE_FILE,
		'tsconfig.base.json',
		'package.json',
		LOCKFILES[pm],
		...(pm === 'pnpm' ? ['pnpm-workspace.yaml'] : []),
	]

	return [...new Set(entries)].map(entry => `            - ${JSON.stringify(entry)}`).join('\n')
}

function deployWorkflow(
	m: Manifest,
	appName: string,
	app: AppConfig,
	scripts: Record<string, string>,
	nodeVersion: string,
	packageGlobs: string[],
	pins: ActionPins
): string {
	const pm = m.packageManager

	return `# Generated by spool ci. The deploy command is copied from spool.json;
# rerun \`spool ci --force\` after changing it there. Spool cannot know your
# default branch, so change the branches list below if it is not main.
name: Deploy ${appName}

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
${pathFilters(m, app, packageGlobs)}

permissions:
    contents: read

concurrency:
    group: \${{ github.workflow }}-\${{ github.ref }}
    cancel-in-progress: true

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
${setupSteps(pm, nodeVersion, pins)}${checkSteps(pm, scripts)}

    deploy:
        needs: check
        runs-on: ubuntu-latest
        permissions:
            contents: read
            # Add what your deploy command needs, e.g. id-token: write for OIDC.
        steps:
${setupSteps(pm, nodeVersion, pins)}
            - name: Build
              working-directory: ${JSON.stringify(app.path)}
              run: ${pm} run build

            # Add the secrets your deploy command needs, e.g.
            # env:
            #     CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
            - name: Deploy
              working-directory: ${JSON.stringify(app.path)}
              run: ${JSON.stringify(app.deploy!)}
`
}

const LOCKFILES = {
	pnpm: 'pnpm-lock.yaml',
	npm: 'package-lock.json',
	yarn: 'yarn.lock',
} as const

const INSTALL_COMMANDS = {
	pnpm: 'pnpm install --frozen-lockfile',
	npm: 'npm ci',
	yarn: 'yarn install --frozen-lockfile',
} as const
