/*
 *   IMPORTS
 ***************************************************************************************************/
import { HELPER_FILE, type AppConfig, type Manifest } from '../config.js'
import type { FileMap } from '../filemap.js'

/*
 *   GITHUB WORKFLOWS
 ***************************************************************************************************/
const CHECK_STEPS: { script: string; label: string }[] = [
	{ script: 'doctor', label: 'Doctor' },
	{ script: 'type-check', label: 'Type check' },
	{ script: 'lint', label: 'Lint' },
	{ script: 'test', label: 'Test' },
	{ script: 'build', label: 'Build' },
]

export function ciWorkflows(m: Manifest, scripts: Record<string, string> = {}): FileMap {
	const files: FileMap = { '.github/workflows/ci.yml': checkWorkflow(m, scripts) }

	for (const [name, app] of Object.entries(m.apps)) {
		if (!app.deploy) continue

		files[`.github/workflows/deploy-${name}.yml`] = ciWorkflow(m, name, app)
	}

	return files
}

function checkWorkflow(m: Manifest, scripts: Record<string, string>): string {
	const pm = m.packageManager
	const steps = CHECK_STEPS.filter(step => scripts[step.script] !== undefined)
		.map(
			step => `
            - name: ${step.label}
              run: ${pm} run ${step.script}`
		)
		.join('\n')

	return `# Generated by spool ci. Checks the whole workspace; the deploy-*.yml
# workflows ship individual apps. Spool cannot know your default branch, so
# change the branches list below if it is not main.
name: CI

on:
    workflow_dispatch:
    pull_request:
    push:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
${pnpmSetup(pm)}
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: '${pm}'

            - name: Install
              run: ${INSTALL_COMMANDS[pm]}
${steps}
`
}

/** pnpm needs its own setup action before setup-node can cache for it. */
function pnpmSetup(pm: Manifest['packageManager']): string {
	return pm === 'pnpm' ? '\n            - uses: pnpm/action-setup@v6\n' : ''
}

const LOCKFILES = {
	pnpm: 'pnpm-lock.yaml',
	npm: 'package-lock.json',
	yarn: 'yarn.lock',
} as const

const INSTALL_COMMANDS = {
	pnpm: 'pnpm install --frozen-lockfile',
	npm: 'npm ci',
	yarn: 'yarn install --frozen-lockfile',
} as const

function ciWorkflow(m: Manifest, appName: string, app: AppConfig): string {
	const pm = m.packageManager

	return `# Generated by spool ci. The deploy command is copied from spool.json;
# rerun \`spool ci --force\` after changing it there. Spool cannot know your
# default branch, so change the branches list below if it is not main.
name: Deploy ${appName}

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - 'apps/${appName}/**'
            - 'spool.json'
            - '${HELPER_FILE}'
            - 'package.json'
            - '${LOCKFILES[pm]}'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
${pnpmSetup(pm)}
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: '${pm}'

            - name: Install
              run: ${INSTALL_COMMANDS[pm]}

            - name: Build
              working-directory: ${app.path}
              run: ${pm} run build

            # Add the secrets your deploy command needs, e.g.
            # env:
            #     CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
            - name: Deploy
              working-directory: ${app.path}
              run: ${app.deploy}
`
}

/*
 *   APP FILES
 ***************************************************************************************************/
/** The expose map a fresh remote starts with; the entry differs by contract. */
