/*
 *   IMPORTS
 ***************************************************************************************************/
import { mkdir, writeFile, readFile, access } from 'node:fs/promises'
import { constants, existsSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import * as p from '@clack/prompts'
import type { FileMap } from './filemap.js'
import { sameContent, type Provenance } from './provenance.js'
import { log } from '../util/logger.js'

/*
 *   TYPES
 ***************************************************************************************************/
export interface WriteResult {
	written: string[]
	skipped: string[]
}

/*
 *   WRITE
 ***************************************************************************************************/
async function exists(p: string): Promise<boolean> {
	try {
		await access(p, constants.F_OK)
		return true
	} catch {
		return false
	}
}

export async function writeFiles(
	baseDir: string,
	files: FileMap,
	opts: { force?: boolean; provenance?: Provenance } = {}
): Promise<WriteResult> {
	const results = await Promise.all(
		Object.entries(files).map(async ([rel, content]): Promise<[string, boolean]> => {
			const target = join(baseDir, rel)
			if (!opts.force && (await exists(target))) return [rel, false]

			await mkdir(dirname(target), { recursive: true })
			await writeFile(target, content, 'utf8')

			opts.provenance?.record(baseDir, rel, content)
			return [rel, true]
		})
	)

	return {
		written: results.filter(([, wrote]) => wrote).map(([rel]) => rel),
		skipped: results.filter(([, wrote]) => !wrote).map(([rel]) => rel),
	}
}

/*
 *   OWNERSHIP-AWARE WRITES
 ***************************************************************************************************/
const GENERATED_MARKER = 'Generated by spool'
type OverwriteReason = 'edited' | 'unverified' | 'untracked'
const REASONS: Record<OverwriteReason, string> = {
	edited: 'has local changes since spool wrote it',
	unverified:
		'predates spool keeping track of what it wrote, so your edits cannot be told from its own output',
	untracked: 'has no record of being written by spool, so it may be yours',
}

// Files older spool versions wrote without a marker or a record. Byte-equal means still ours.
const LEGACY_OUTPUTS = ['/*\n  Access-Control-Allow-Origin: *\n']

const isLegacyOutput = (content: string): boolean =>
	LEGACY_OUTPUTS.some(legacy => sameContent(content, legacy))

export class OwnedWriter {
	public changed = 0
	public readonly added = new Set<string>()
	protected skipped = 0
	/** Set once the user answers "every file" either way. */
	private overwriteAll: boolean | null = null

	constructor(
		protected readonly root: string,
		protected readonly dryRun: boolean,
		protected readonly provenance: Provenance | null,
		protected readonly force: boolean | string[]
	) {}

	protected get verb(): string {
		return this.dryRun ? 'would update' : 'updated'
	}

	get skippedCount(): number {
		return this.skipped
	}

	/** Writes unconditionally; used internally once ownership has cleared. */
	async replace(dir: string, rel: string, content: string, label: string): Promise<void> {
		const target = join(dir, rel)
		const existing = existsSync(target) ? await readFile(target, 'utf8') : null
		if (existing !== null && sameContent(existing, content)) return

		if (existing === null) this.added.add(rel)

		this.changed++
		log.step(`${label}: ${this.verb} ${rel}`)
		if (!this.dryRun) {
			await mkdir(dirname(target), { recursive: true })
			await writeFile(target, content, 'utf8')
			this.provenance?.record(dir, rel, content)
		}
	}

	/** Writes a generated file, asking (or deferring to --force) before overwriting an edited one. */
	async replaceGenerated(
		dir: string,
		rel: string,
		content: string,
		label: string
	): Promise<void> {
		const target = join(dir, rel)
		if (existsSync(target)) {
			const existing = await readFile(target, 'utf8')

			if (sameContent(existing, content)) {
				if (!this.dryRun) this.provenance?.record(dir, rel, content)
				return
			}

			if (!(await this.mayOverwrite(dir, rel, existing, label))) return
		}
		await this.replace(dir, rel, content, label)
	}

	private async mayOverwrite(
		dir: string,
		rel: string,
		existing: string,
		label: string
	): Promise<boolean> {
		switch (this.provenance?.ownership(dir, rel, existing) ?? 'unknown') {
			case 'ours':
				return true

			case 'owned':
				if (this.forces(dir, rel)) return true

				log.step(`${label}: ${rel} is yours; leaving it alone.`)
				this.skipped++

				return false

			case 'edited':
				return this.confirmOverwrite(dir, rel, label, 'edited')

			case 'unknown':
				if (isLegacyOutput(existing)) return true

				return this.confirmOverwrite(
					dir,
					rel,
					label,
					existing.includes(GENERATED_MARKER) ? 'unverified' : 'untracked'
				)
		}
	}

	private async confirmOverwrite(
		dir: string,
		rel: string,
		label: string,
		reason: OverwriteReason
	): Promise<boolean> {
		if (this.forces(dir, rel)) return true

		if (this.dryRun) {
			log.step(`${label}: ${rel} ${REASONS[reason]}; would ask before overwriting`)
			this.skipped++

			return false
		}

		if (this.overwriteAll !== null) {
			if (!this.overwriteAll) this.keep(dir, rel)

			return this.overwriteAll
		}

		if (!process.stdin.isTTY) {
			log.warn(
				`${label}: ${rel} ${REASONS[reason]}, leaving it alone. Rerun with --force to overwrite.`
			)

			this.skipped++
			return false
		}

		const answer = await p.select({
			message: `${label}: ${rel} ${REASONS[reason]}.`,
			options: [
				{ value: 'keep', label: 'Keep my version' },
				{ value: 'overwrite', label: 'Overwrite it with the generated file' },
				{ value: 'keep-all', label: 'Keep mine, for every file' },
				{ value: 'overwrite-all', label: 'Overwrite every file' },
			],
			initialValue: 'keep',
		})

		if (p.isCancel(answer) || answer === 'keep') {
			this.keep(dir, rel)
			return false
		}

		if (answer === 'overwrite') return true

		this.overwriteAll = answer === 'overwrite-all'
		if (!this.overwriteAll) this.keep(dir, rel)

		return this.overwriteAll
	}

	/** --force with no paths forces every file; with paths, only those. */
	protected forces(dir: string, rel: string): boolean {
		if (typeof this.force === 'boolean') return this.force

		const target = relative(this.root, join(dir, rel)).split(sep).join('/')

		return this.force.some(entry => entry.split(sep).join('/') === target)
	}

	protected keep(dir: string, rel: string): void {
		this.provenance?.claim(dir, rel)
		this.skipped++
	}

	async add(dir: string, rel: string, content: string, label: string): Promise<void> {
		if (existsSync(join(dir, rel))) return

		this.changed++
		this.added.add(rel)
		log.step(`${label}: ${this.dryRun ? 'would add' : 'added'} ${rel}`)

		if (!this.dryRun) {
			await mkdir(dirname(join(dir, rel)), { recursive: true })
			await writeFile(join(dir, rel), content, 'utf8')

			this.provenance?.record(dir, rel, content)
		}
	}
}
