/*
 *   IMPORTS
 ***************************************************************************************************/
import { HELPER_FILE, type AppConfig, type Manifest } from './config.js'
import { PRETTIER_OPTIONS } from './format.js'
import { PNPM_VERSION, TOOLCHAIN } from './versions.js'
import { pascalCase } from '../util/names.js'

/*
 *   TYPES
 ***************************************************************************************************/
/** A flat map of relative file path -> file contents. */
export type FileMap = Record<string, string>

/*
 *   HELPERS
 ***************************************************************************************************/
const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

/** Ambient module declarations so hosts can `import` their remotes' exposes. */
const remoteTypings = (remotes: string[]): string =>
	remotes
		.map(
			r =>
				`declare module "${r}/App" {\n  const Component: React.ComponentType;\n  export default Component;\n}\n`
		)
		.join('')

/** Relative import path from an app folder up to the workspace-root helper. */
const helperImport = (appPath: string): string => {
	const depth = appPath.split('/').filter(Boolean).length
	return `${'../'.repeat(depth)}${HELPER_FILE.replace(/\.ts$/, '')}`
}

/** The runtime helper as a writable FileMap; `spool add` uses it to self-heal. */
export function helperFile(): FileMap {
	return { [HELPER_FILE]: spoolViteHelper() }
}

/*
 *   WORKSPACE FILES
 ***************************************************************************************************/
/** Workspace-root files, generated once by `spool create`. */
export function workspaceFiles(m: Manifest): FileMap {
	const files: FileMap = {
		'spool.json': json(m),
		...helperFile(),
		'.prettierrc': json(PRETTIER_OPTIONS),
		// Lockfiles are generated by the package manager in its own style.
		'.prettierignore': `pnpm-lock.yaml\npackage-lock.json\nyarn.lock\n.yarn/\n`,
		'package.json': workspacePackageJson(m),
		'.gitignore': gitignore(m),
		'tsconfig.base.json': json({
			compilerOptions: {
				target: 'ES2022',
				lib: ['ES2022', 'DOM', 'DOM.Iterable'],
				module: 'ESNext',
				moduleResolution: 'Bundler',
				jsx: 'react-jsx',
				strict: true,
				skipLibCheck: true,
				esModuleInterop: true,
				forceConsistentCasingInFileNames: true,
				isolatedModules: true,
				noEmit: true,
			},
		}),
		// Root-level project so editors type-check the runtime helper.
		'tsconfig.json': json({
			extends: './tsconfig.base.json',
			include: [HELPER_FILE],
		}),
		'README.md': workspaceReadme(m),
	}

	// pnpm declares its workspace (and its postinstall-script allowlist) in a
	// dedicated file; npm and yarn read a `workspaces` field in package.json.
	if (m.packageManager === 'pnpm') {
		files['pnpm-workspace.yaml'] =
			`packages:\n  - "apps/*"\n  - "packages/*"\n\n# esbuild (via vite) needs its postinstall to fetch the platform binary.\n# allowBuilds is the pnpm 11+ spelling; onlyBuiltDependencies covers pnpm 10.\nallowBuilds:\n  esbuild: true\nonlyBuiltDependencies:\n  - esbuild\n`
	}

	// Yarn Berry defaults to Plug'n'Play, which breaks Vite and Module
	// Federation. Pin the node_modules linker; Yarn Classic ignores this file.
	if (m.packageManager === 'yarn') {
		files['.yarnrc.yml'] =
			`# Use the node_modules linker instead of Plug'n'Play so Vite and Module\n# Federation resolve dependencies the way they expect. Honored by Yarn 3+;\n# Yarn 1 ignores this file and already uses node_modules.\nnodeLinker: node-modules\n`
	}
	return files
}

function gitignore(m: Manifest): string {
	const base = `node_modules/\ndist/\n*.tsbuildinfo\n.DS_Store\n*.log\n`
	if (m.packageManager !== 'yarn') return base
	// Yarn Berry writes these; the allowlist keeps committed Berry assets while
	// ignoring the cache and PnP files. Harmless under Yarn Classic.
	return `${base}\n# Yarn Berry\n.yarn/*\n!.yarn/patches\n!.yarn/plugins\n!.yarn/releases\n!.yarn/sdks\n!.yarn/versions\n.pnp.*\n`
}

/** Within vite's supported range; Node 20 is EOL and pnpm 11 needs 22.13+. */
const NODE_RANGE = '>=22.12.0'

function workspacePackageJson(m: Manifest): string {
	const pkg: Record<string, unknown> = {
		name: m.name,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: {
			dev: 'spool dev',
			build: 'spool build',
			doctor: 'spool doctor',
		},
	}
	if (m.packageManager === 'pnpm') {
		// pnpm/action-setup and corepack read the version from here.
		pkg.packageManager = `pnpm@${PNPM_VERSION}`
	} else {
		pkg.workspaces = ['apps/*', 'packages/*']
	}
	// The root tsconfig type-checks spool.vite.ts, which uses node builtins.
	pkg.devDependencies = {
		'@types/node': TOOLCHAIN['@types/node'],
		typescript: TOOLCHAIN.typescript,
	}
	return json(pkg)
}

function workspaceReadme(m: Manifest): string {
	return `# ${m.name}\n\nMicro-frontend workspace scaffolded with [spool](https://github.com/bkincz/spool).\n\nAll federation wiring lives in \`spool.json\`; each app's \`vite.config.ts\` reads it\nthrough \`spool.vite.ts\` at startup, so editing the manifest is all you ever do.\n\n## Commands\n\n\`\`\`bash\n${m.packageManager} install   # install all apps\nspool dev        # run host + remotes together\nspool build      # coordinated production build\nspool add <name> # add a host or remote app\nspool doctor     # check ports, wiring and shared deps\n\`\`\`\n\n## Deploying remotes\n\nA host resolves each remote in this order:\n\n1. \`SPOOL_REMOTE_<NAME>\` env var (ad-hoc override, e.g. point one remote at staging)\n2. the remote's \`url\` in \`spool.json\` (its deployed \`mf-manifest.json\`, used in production builds)\n3. \`http://localhost:<port>/mf-manifest.json\` (local dev)\n`
}

/*
 *   RUNTIME HELPER
 ***************************************************************************************************/
/**
 * The workspace-root `spool.vite.ts`. Apps' vite configs call `spoolApp(name)`
 * from it, which reads spool.json at config load time. Dependency-free
 * (node:fs and node:path only) so it runs in any app.
 */
function spoolViteHelper(): string {
	return `/**
 * Generated by spool. Reads spool.json when Vite loads the config and derives
 * the app's dev server and Module Federation settings. Edit spool.json, not
 * this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export interface SpoolAppEntry {
  type: "host" | "remote";
  path: string;
  port: number;
  url?: string;
  remotes?: string[];
  exposes?: Record<string, string>;
}

export interface SpoolManifest {
  name: string;
  shared?: string[];
  apps: Record<string, SpoolAppEntry>;
}

export interface SpoolAppConfig {
  /** Vite server/preview settings for this app. */
  server: { port: number; strictPort: boolean };
  /** Options for the federation() plugin from @module-federation/vite. */
  federation: {
    name: string;
    filename?: string;
    manifest?: boolean;
    remotes?: Record<string, string>;
    exposes?: Record<string, string>;
    shared: string[];
  };
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.vite: no spool.json found above " + from);
    dir = parent;
  }
}

/**
 * Remote lookup order: SPOOL_REMOTE_<NAME> env var, the remote's "url" in
 * spool.json (production builds only, so dev keeps hitting local servers),
 * then the local dev server.
 */
function remoteUrl(name: string, app: SpoolAppEntry, command: SpoolCommand): string {
  const envKey = "SPOOL_REMOTE_" + name.toUpperCase().replace(/-/g, "_");
  const deployed = command === "build" ? app.url : undefined;
  return process.env[envKey] ?? deployed ?? "http://localhost:" + app.port + "/mf-manifest.json";
}

export type SpoolCommand = "build" | "serve";

export function spoolApp(
  name: string,
  from: string = process.cwd(),
  command: SpoolCommand = "serve"
): SpoolAppConfig {
  const manifest = JSON.parse(readFileSync(findManifest(from), "utf8")) as SpoolManifest;
  const app = manifest.apps[name];
  if (!app) throw new Error('spool.vite: no app named "' + name + '" in spool.json');

  const shared = manifest.shared ?? [];
  const server = { port: app.port, strictPort: true };

  if (app.type === "host") {
    const remotes: Record<string, string> = {};
    for (const remote of app.remotes ?? []) {
      const target = manifest.apps[remote];
      if (!target) {
        throw new Error('spool.vite: host "' + name + '" references unknown remote "' + remote + '"');
      }
      remotes[remote] = remoteUrl(remote, target, command);
    }
    return { server, federation: { name, remotes, shared } };
  }

  return {
    server,
    federation: {
      name,
      filename: "remoteEntry.js",
      // Dev serves mf-manifest.json automatically; builds only emit it with
      // this flag, and hosts load remotes by their manifest URL.
      manifest: true,
      exposes: app.exposes ?? {},
      shared,
    },
  };
}
`
}

/*
 *   CI WORKFLOWS
 ***************************************************************************************************/
export function ciWorkflows(m: Manifest): FileMap {
	const files: FileMap = {}
	for (const [name, app] of Object.entries(m.apps)) {
		if (!app.deploy) continue
		files[`.github/workflows/deploy-${name}.yml`] = ciWorkflow(m, name, app)
	}
	return files
}

const LOCKFILES = {
	pnpm: 'pnpm-lock.yaml',
	npm: 'package-lock.json',
	yarn: 'yarn.lock',
} as const

const INSTALL_COMMANDS = {
	pnpm: 'pnpm install --frozen-lockfile',
	npm: 'npm ci',
	yarn: 'yarn install --frozen-lockfile',
} as const

function ciWorkflow(m: Manifest, appName: string, app: AppConfig): string {
	const pm = m.packageManager
	const pnpmSetup =
		pm === 'pnpm'
			? `
            - uses: pnpm/action-setup@v6
`
			: ''

	return `# Generated by spool ci. The deploy command is copied from spool.json;
# rerun \`spool ci --force\` after changing it there.
name: Deploy ${appName}

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - 'apps/${appName}/**'
            - 'spool.json'
            - '${HELPER_FILE}'
            - 'package.json'
            - '${LOCKFILES[pm]}'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
${pnpmSetup}
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: '${pm}'

            - name: Install
              run: ${INSTALL_COMMANDS[pm]}

            - name: Build
              working-directory: ${app.path}
              run: ${pm} run build

            # Add the secrets your deploy command needs, e.g.
            # env:
            #     CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
            - name: Deploy
              working-directory: ${app.path}
              run: ${app.deploy}
`
}

/*
 *   APP FILES
 ***************************************************************************************************/
export function appFiles(m: Manifest, appName: string, app: AppConfig): FileMap {
	const isHost = app.type === 'host'
	const files: FileMap = {
		'package.json': appPackageJson(appName),
		'tsconfig.json': appTsConfig(),
		'vite.config.ts': viteConfig(appName, app),
		'index.html': indexHtml(appName),
		'src/main.tsx': mainTsx(),
		'src/App.tsx': isHost ? hostApp(appName, app.remotes) : remoteApp(appName),
		'src/vite-env.d.ts': `/// <reference types="vite/client" />\n`,
	}

	// Hosts fetch remote assets cross-origin in production, and static hosts
	// send no CORS headers by default. Cloudflare Pages and Netlify both read
	// this file; it is inert elsewhere.
	if (!isHost) {
		files['public/_headers'] = `/*\n  Access-Control-Allow-Origin: *\n`
	}
	if (isHost && app.remotes.length) {
		files['src/remotes.d.ts'] = remoteTypings(app.remotes)
	}
	return files
}

/**
 * Host files to rewrite when its remotes change. Only the ambient typings;
 * the vite config reads spool.json itself.
 */
export function hostWiringFiles(host: AppConfig): FileMap {
	if (!host.remotes.length) return {}
	return { 'src/remotes.d.ts': remoteTypings(host.remotes) }
}

/*
 *   FILE BUILDERS
 ***************************************************************************************************/
function appPackageJson(appName: string): string {
	return json({
		name: appName,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: {
			dev: 'vite',
			build: 'vite build',
			preview: 'vite preview',
		},
		dependencies: {
			react: TOOLCHAIN.react,
			'react-dom': TOOLCHAIN['react-dom'],
		},
		devDependencies: {
			'@module-federation/vite': TOOLCHAIN['@module-federation/vite'],
			// The vite config and spool.vite.ts use node builtins, so apps
			// need node types to type-check.
			'@types/node': TOOLCHAIN['@types/node'],
			'@types/react': TOOLCHAIN['@types/react'],
			'@types/react-dom': TOOLCHAIN['@types/react-dom'],
			'@vitejs/plugin-react': TOOLCHAIN['@vitejs/plugin-react'],
			typescript: TOOLCHAIN.typescript,
			vite: TOOLCHAIN.vite,
		},
	})
}

function appTsConfig(): string {
	return json({
		extends: '../../tsconfig.base.json',
		include: ['src', 'vite.config.ts'],
	})
}

function viteConfig(appName: string, app: AppConfig): string {
	return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { federation } from "@module-federation/vite";
import { spoolApp } from "${helperImport(app.path)}";

// Generated by spool. Wiring comes from spool.json via spool.vite.ts at
// startup. Edit spool.json, not this file. The command tells the helper
// whether deployed remote urls apply (build) or local dev servers do (serve).
export default defineConfig(({ command }) => {
  const app = spoolApp(${JSON.stringify(appName)}, import.meta.dirname, command);
  return {
    server: app.server,
    preview: app.server,
    plugins: [react(), federation(app.federation)],
    // Module Federation needs top-level await; lock the build target.
    build: { target: "esnext", minify: false },
  };
});
`
}

function indexHtml(appName: string): string {
	return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

function mainTsx(): string {
	return `import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`
}

function hostApp(appName: string, remotes: string[]): string {
	const imports = remotes
		.map(r => `const ${pascalCase(r)} = lazy(() => import("${r}/App"));`)
		.join('\n')
	const mounts = remotes
		.map(
			r =>
				`        <section>
          <h2>${r}</h2>
          <Suspense fallback={<p>Loading ${r}...</p>}>
            <${pascalCase(r)} />
          </Suspense>
        </section>`
		)
		.join('\n')
	const noRemotes = `// No remotes wired yet. Add one with \`spool add <name> --host ${appName}\`.`
	return `import { lazy, Suspense } from "react";

${imports || noRemotes}

export default function App() {
  return (
    <main style={{ fontFamily: "system-ui", padding: 24 }}>
      <h1>${appName} (host)</h1>
${mounts || '      <p>No remotes mounted yet.</p>'}
    </main>
  );
}
`
}

function remoteApp(appName: string): string {
	return `export default function App() {
  return (
    <div style={{ fontFamily: "system-ui", padding: 16, border: "1px solid #ccc" }}>
      <strong>${appName}</strong>: a remote module exposed via Module Federation.
    </div>
  );
}
`
}
