/*
 *   IMPORTS
 ***************************************************************************************************/
import { HELPER_FILE, type AppConfig, type Framework, type Manifest } from './config.js'
import type { FileMap } from './filemap.js'
import { PRETTIER_OPTIONS } from './format.js'
import { appDependencies, NODE_RANGE, PNPM_VERSION, rootDevDependencies } from './versions.js'
import { yamlKey } from '../util/names.js'
import {
	ALIAS_FILE,
	remoteAliasModule,
	remoteStubs,
	TEST_SCRIPTS,
	typeCheckAll,
	vitestConfig,
} from './templates/quality.js'
import {
	NO_EXTRAS,
	TEMPLATES,
	remoteRefs,
	type RemoteRef,
	type TemplateExtras,
} from './templates/index.js'
import { helperFiles } from './templates/helpers.js'
import { sentryVitePlugin } from './templates/sentry.js'
import { federationFiles } from './templates/composition.js'

/*
 *   TYPES
 ***************************************************************************************************/

/*
 *   HELPERS
 ***************************************************************************************************/
const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

/** Relative import path from an app folder up to the workspace-root helper. */
const helperImport = (appPath: string): string => {
	const depth = appPath.split('/').filter(Boolean).length
	return `${'../'.repeat(depth)}${HELPER_FILE.replace(/\.ts$/, '')}`
}

/** The generated helpers as a writable FileMap; `spool add` uses it to self-heal. */

/**
 * Reads spool.json at import time like the vite helper does, so anything
 * built on it stays right as apps come and go. A hand-kept copy of the app
 * list is the thing this exists to delete.
 */
/*
 *   WORKSPACE FILES
 ***************************************************************************************************/
/** Workspace-root files, generated once by `spool create`. */
export function workspaceFiles(m: Manifest, allowBuilds: string[] = []): FileMap {
	const files: FileMap = {
		'spool.json': json(m),
		...helperFiles(),
		'.prettierrc': json(PRETTIER_OPTIONS),
		// Lockfiles are generated by the package manager in its own style.
		'.prettierignore': `pnpm-lock.yaml\npackage-lock.json\nyarn.lock\n.yarn/\n`,
		'package.json': workspacePackageJson(m),
		'.gitignore': gitignore(m),
		'tsconfig.base.json': json({
			compilerOptions: {
				target: 'ES2022',
				lib: ['ES2022', 'DOM', 'DOM.Iterable'],
				module: 'ESNext',
				moduleResolution: 'Bundler',
				strict: true,
				skipLibCheck: true,
				esModuleInterop: true,
				forceConsistentCasingInFileNames: true,
				isolatedModules: true,
				noEmit: true,
			},
		}),
		// Root-level project so editors type-check the runtime helper.
		'tsconfig.json': json({
			extends: './tsconfig.base.json',
			// TypeScript 6 stopped auto-including @types, and the helper is node code.
			compilerOptions: { types: ['node'] },
			include: [HELPER_FILE],
		}),
		'README.md': workspaceReadme(m),
	}

	// pnpm declares its workspace (and its postinstall-script allowlist) in a
	// dedicated file; npm and yarn read a `workspaces` field in package.json.
	if (m.packageManager === 'pnpm') {
		const builds = [...new Set(['esbuild', ...allowBuilds])].sort()
		files['pnpm-workspace.yaml'] =
			`packages:\n  - "apps/*"\n  - "packages/*"\n\n# These postinstall scripts fetch platform binaries (esbuild via vite).\n# allowBuilds is the pnpm 11+ spelling; onlyBuiltDependencies covers pnpm 10.\nallowBuilds:\n${builds.map(build => `  ${yamlKey(build)}: true`).join('\n')}\nonlyBuiltDependencies:\n${builds.map(build => `  - ${yamlKey(build)}`).join('\n')}\n`
	}

	// Yarn Berry defaults to Plug'n'Play, which breaks Vite and Module
	// Federation. Pin the node_modules linker; Yarn Classic ignores this file.
	if (m.packageManager === 'yarn') {
		files['.yarnrc.yml'] =
			`# Use the node_modules linker instead of Plug'n'Play so Vite and Module\n# Federation resolve dependencies the way they expect. Honored by Yarn 3+;\n# Yarn 1 ignores this file and already uses node_modules.\nnodeLinker: node-modules\n`
	}
	return files
}

function gitignore(m: Manifest): string {
	const base = `node_modules/\ndist/\n*.tsbuildinfo\n.DS_Store\n*.log\n`
	if (m.packageManager !== 'yarn') return base
	// Yarn Berry writes these; the allowlist keeps committed Berry assets while
	// ignoring the cache and PnP files. Harmless under Yarn Classic.
	return `${base}\n# Yarn Berry\n.yarn/*\n!.yarn/patches\n!.yarn/plugins\n!.yarn/releases\n!.yarn/sdks\n!.yarn/versions\n.pnp.*\n`
}

export function workspaceScripts(m: Manifest): Record<string, string> {
	const scripts: Record<string, string> = {
		dev: 'spool dev',
		build: 'spool build',
		preview: 'spool preview',
		doctor: 'spool doctor',
		'type-check': typeCheckAll(m),
	}

	if (m.addons.includes('lint')) scripts.lint = 'eslint .'
	if (m.addons.includes('test')) scripts.test = testAll(m)

	return scripts
}

/** Run every package that has a test script, however this manager spells it. */
function testAll(m: Manifest): string {
	if (m.packageManager === 'npm') return 'npm run test --workspaces --if-present'
	if (m.packageManager === 'yarn') return 'yarn workspaces foreach -A run test'
	return 'pnpm -r test'
}

function workspacePackageJson(m: Manifest): string {
	const pkg: Record<string, unknown> = {
		name: m.name,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: workspaceScripts(m),
	}

	if (m.packageManager === 'pnpm') {
		// pnpm/action-setup and corepack read the version from here.
		pkg.packageManager = `pnpm@${PNPM_VERSION}`
	} else {
		pkg.workspaces = ['apps/*', 'packages/*']
	}

	pkg.devDependencies = sortKeys(rootDevDependencies(m))
	return json(pkg)
}

function workspaceReadme(m: Manifest): string {
	return `# ${m.name}\n\nMicro-frontend workspace scaffolded with [spool](https://github.com/bkincz/spool).\n\nAll federation wiring lives in \`spool.json\`; each app's \`vite.config.ts\` reads it\nthrough \`spool.vite.ts\` at startup, so editing the manifest is all you ever do.\n\n## Commands\n\n\`\`\`bash\n${m.packageManager} install    # install all apps\nspool dev           # run host + remotes together\nspool build         # coordinated production build\nspool preview       # serve the built apps locally\nspool deploy        # run each app's deploy command\nspool add <name>    # add a host or remote app\nspool remove <name> # remove an app and unwire it\nspool ci            # generate per-app deploy workflows\nspool upgrade       # sync generated files to the installed spool\nspool doctor        # check ports, wiring and shared deps\n\`\`\`\n\n## Deploying remotes\n\nA host resolves each remote in this order:\n\n1. \`SPOOL_REMOTE_<NAME>\` env var (ad-hoc override, e.g. point one remote at staging)\n2. the remote's \`urls\` entry for \`SPOOL_ENV\` / \`--env\` (production builds only)\n3. the remote's \`url\` in \`spool.json\` (its deployed \`mf-manifest.json\`, used in production builds)\n4. \`http://localhost:<port>/mf-manifest.json\` (local dev)\n`
}

/*
 *   RUNTIME HELPER
 ***************************************************************************************************/
/**
 * The workspace-root `spool.vite.ts`. Apps' vite configs call `spoolApp(name)`
 * from it, which reads spool.json at config load time. Dependency-free
 * (node:fs and node:path only) so it runs in any app.
 */
/*
 *   CI WORKFLOWS
 ***************************************************************************************************/
/** Steps the check workflow runs, in the order it runs them. */
export function defaultExposes(framework: Framework): Record<string, string> {
	return { './App': TEMPLATES[framework].exposeEntry }
}

export function appFiles(
	m: Manifest,
	appName: string,
	app: AppConfig,
	extras: TemplateExtras = NO_EXTRAS
): FileMap {
	const isHost = app.type === 'host'
	const refs = app.remotes.length ? remoteRefs(m, app) : []
	const files: FileMap = {
		'package.json': appPackageJson(m, appName, app, extras),
		'tsconfig.json': appTsConfig(app.framework),
		'index.html': indexHtml(appName, app.framework),
		'src/vite-env.d.ts': TEMPLATES[app.framework].viteEnv,
		...TEMPLATES[app.framework].sourceFiles(appName, isHost, refs, extras),
		...appConfigFiles(appName, app, m.addons.includes('sentry')),
	}

	if (refs.length) {
		files['src/remotes.d.ts'] = remoteTypings(refs)
	}
	if (m.addons.includes('test')) {
		files['vitest.config.ts'] = vitestConfig()
		files[ALIAS_FILE] = remoteAliasModule(m, app)
		Object.assign(files, remoteStubs(m, app))
	}
	return files
}

/**
 * The generated files `spool upgrade` refreshes on every run: the vite config
 * and, for remotes, the CORS headers static hosts need.
 */
export function appConfigFiles(appName: string, app: AppConfig, sentry = false): FileMap {
	const files: FileMap = { 'vite.config.ts': viteConfig(appName, app, sentry) }
	// Hosts fetch remote assets cross-origin in production, and static hosts
	// send no CORS headers by default. Cloudflare Pages and Netlify both read
	// this file; it is inert elsewhere.
	if (app.type === 'remote') {
		files['public/_headers'] = `/*\n  Access-Control-Allow-Origin: *\n`
	}
	return files
}

/**
 * Host files to rewrite when its remotes change. Only the ambient typings;
 * the vite config reads spool.json itself.
 */
export function hostWiringFiles(m: Manifest, host: AppConfig): FileMap {
	const files: FileMap = {}
	if (host.type !== 'host' && !host.remotes.length) return files
	if (host.remotes.length) files['src/remotes.d.ts'] = remoteTypings(remoteRefs(m, host))

	// The registry and the <Remote> primitive both depend on the host's remotes
	// (the primitive imports the react bridge only when one needs it), so both
	// are regenerated together whenever the remotes change.
	if (m.addons.includes('federation')) Object.assign(files, federationFiles(m, host))

	// Only the alias map names the remotes; vitest.config.ts stays the user’s.
	if (m.addons.includes('test')) {
		files[ALIAS_FILE] = remoteAliasModule(m, host)
		Object.assign(files, remoteStubs(m, host))
	}
	return files
}

/*
 *   FILE BUILDERS
 ***************************************************************************************************/
function appPackageJson(
	m: Manifest,
	appName: string,
	app: AppConfig,
	extras: TemplateExtras
): string {
	const { dependencies, devDependencies } = appDependencies(m, app)

	// The example button lives in the ladle ui workspace package; npm and yarn
	// link workspace packages by bare name, pnpm needs the workspace protocol.
	if (extras.uiButton && app.framework === 'react' && app.type === 'remote') {
		dependencies.ui = m.packageManager === 'pnpm' ? 'workspace:*' : '*'
	}

	return json({
		name: appName,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: {
			dev: 'vite',
			build: 'vite build',
			preview: 'vite preview',
			'type-check': 'tsc --noEmit',
			...(m.addons.includes('test') ? TEST_SCRIPTS : {}),
		},
		dependencies: sortKeys(dependencies),
		devDependencies: sortKeys(devDependencies),
	})
}

function sortKeys(record: Record<string, string>): Record<string, string> {
	return Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)))
}

function appTsConfig(framework: Framework): string {
	// Compiler options like the JSX runtime are per app, so one framework's
	// settings never leak into another's through the shared base config. `@`
	// maps to src (matched by the vite alias) so apps import from "@/...".
	return json({
		extends: '../../tsconfig.base.json',
		compilerOptions: {
			...TEMPLATES[framework].compilerOptions,
			paths: { '@/*': ['./src/*'] },
		},
		include: ['src', 'vite.config.ts'],
	})
}

function viteConfig(appName: string, app: AppConfig, sentry: boolean): string {
	const plugin = TEMPLATES[app.framework].vitePlugin
	const sentryPlugin = sentry ? sentryVitePlugin() : undefined

	const imports = [
		'import { defineConfig } from "vite";',
		'import { resolve as resolvePath } from "node:path";',
		plugin.importLine,
		'import { federation } from "@module-federation/vite";',
		...(sentryPlugin ? [sentryPlugin.importLine] : []),
		`import { spoolApp } from "${helperImport(app.path)}";`,
	].join('\n')

	const plugins = [
		`${plugin.call}`,
		'federation(app.federation)',
		...(sentryPlugin ? [sentryPlugin.entry] : []),
	]

	return `${imports}

// Generated by spool. Wiring comes from spool.json via spool.vite.ts at
// startup. Edit spool.json, not this file.
export default defineConfig(({ command }) => {
  const app = spoolApp(${JSON.stringify(appName)}, import.meta.dirname, command);
  return {
    server: app.server,
    preview: app.server,
    resolve: { alias: { "@": resolvePath(import.meta.dirname, "src") } },
    plugins: [${plugins.join(', ')}],
    // Module Federation needs top-level await, so the target is locked.
    build: { target: "esnext", minify: false${sentry ? ', sourcemap: true' : ''} },
  };
});
`
}

function indexHtml(appName: string, framework: Framework): string {
	const entry = TEMPLATES[framework].htmlEntry
	return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${entry}"></script>
  </body>
</html>
`
}

function remoteTypings(refs: RemoteRef[]): string {
	return refs.map(ref => TEMPLATES[ref.framework].remoteTyping(ref)).join('')
}
