/*
 *   IMPORTS
 ***************************************************************************************************/
import {
	HELPER_FILE,
	WORKSPACE_FILE,
	type AppConfig,
	type Framework,
	type Manifest,
} from './config.js'
import { PRETTIER_OPTIONS } from './format.js'
import { appDependencies, PNPM_VERSION, rootDevDependencies } from './versions.js'
import {
	ALIAS_FILE,
	remoteAliasModule,
	remoteStubs,
	TEST_SCRIPTS,
	typeCheckAll,
	vitestConfig,
} from './templates/quality.js'
import {
	NO_EXTRAS,
	TEMPLATES,
	remoteRefs,
	type RemoteRef,
	type TemplateExtras,
} from './templates/index.js'
import { sentryVitePlugin } from './templates/sentry.js'
import { shellHostFiles } from './templates/shell.js'

/*
 *   TYPES
 ***************************************************************************************************/
/** A flat map of relative file path -> file contents. */
export type FileMap = Record<string, string>

/*
 *   HELPERS
 ***************************************************************************************************/
const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

/** Relative import path from an app folder up to the workspace-root helper. */
const helperImport = (appPath: string): string => {
	const depth = appPath.split('/').filter(Boolean).length
	return `${'../'.repeat(depth)}${HELPER_FILE.replace(/\.ts$/, '')}`
}

/** The generated helpers as a writable FileMap; `spool add` uses it to self-heal. */
export function helperFile(): FileMap {
	return {
		[HELPER_FILE]: spoolViteHelper(),
		[WORKSPACE_FILE]: spoolWorkspaceHelper(),
	}
}

/**
 * Reads spool.json at import time like the vite helper does, so anything
 * built on it stays right as apps come and go. A hand-kept copy of the app
 * list is the thing this exists to delete.
 */
function spoolWorkspaceHelper(): string {
	return `/*
 * Generated by spool. Reads spool.json when it is imported, so the app list
 * is never stale. Edit spool.json, not this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export type SpoolFramework = "react" | "svelte" | "vue";

export interface WorkspaceApp {
  name: string;
  type: "host" | "remote";
  framework: SpoolFramework;
  port: number;
  /** Absolute path to the app folder. */
  dir: string;
  /** Absolute path to the app\u2019s src folder. */
  src: string;
  /** Remotes a host consumes; empty for a remote. */
  remotes: string[];
  /** Modules a remote exposes; empty for a host. */
  exposes: Record<string, string>;
}

interface RawApp {
  type: "host" | "remote";
  framework?: SpoolFramework;
  path: string;
  port: number;
  remotes?: string[];
  exposes?: Record<string, string>;
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.workspace: no spool.json found above " + from);
    dir = parent;
  }
}

const manifestPath = findManifest(import.meta.dirname);
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
  name: string;
  shared?: string[];
  addons?: string[];
  apps: Record<string, RawApp>;
};

/** Absolute path to the workspace root, where spool.json lives. */
export const root: string = dirname(manifestPath);

export const workspaceName: string = manifest.name;
export const shared: string[] = manifest.shared ?? [];
export const addons: string[] = manifest.addons ?? [];

export const apps: WorkspaceApp[] = Object.entries(manifest.apps).map(([name, entry]) => ({
  name,
  type: entry.type,
  framework: entry.framework ?? "react",
  port: entry.port,
  dir: join(root, entry.path),
  src: join(root, entry.path, "src"),
  remotes: entry.remotes ?? [],
  exposes: entry.exposes ?? {},
}));

export const hosts: WorkspaceApp[] = apps.filter(entry => entry.type === "host");
export const remotes: WorkspaceApp[] = apps.filter(entry => entry.type === "remote");

/** Every app\u2019s src folder, for sweeps that should cover the whole workspace. */
export const srcDirs: string[] = apps.map(entry => entry.src);

export function app(name: string): WorkspaceApp {
  const found = apps.find(entry => entry.name === name);
  if (!found) throw new Error(\`spool.workspace: no app named "\${name}" in spool.json\`);
  return found;
}
`
}

/*
 *   WORKSPACE FILES
 ***************************************************************************************************/
/** Workspace-root files, generated once by `spool create`. */
export function workspaceFiles(m: Manifest, allowBuilds: string[] = []): FileMap {
	const files: FileMap = {
		'spool.json': json(m),
		...helperFile(),
		'.prettierrc': json(PRETTIER_OPTIONS),
		// Lockfiles are generated by the package manager in its own style.
		'.prettierignore': `pnpm-lock.yaml\npackage-lock.json\nyarn.lock\n.yarn/\n`,
		'package.json': workspacePackageJson(m),
		'.gitignore': gitignore(m),
		'tsconfig.base.json': json({
			compilerOptions: {
				target: 'ES2022',
				lib: ['ES2022', 'DOM', 'DOM.Iterable'],
				module: 'ESNext',
				moduleResolution: 'Bundler',
				strict: true,
				skipLibCheck: true,
				esModuleInterop: true,
				forceConsistentCasingInFileNames: true,
				isolatedModules: true,
				noEmit: true,
			},
		}),
		// Root-level project so editors type-check the runtime helper.
		'tsconfig.json': json({
			extends: './tsconfig.base.json',
			include: [HELPER_FILE],
		}),
		'README.md': workspaceReadme(m),
	}

	// pnpm declares its workspace (and its postinstall-script allowlist) in a
	// dedicated file; npm and yarn read a `workspaces` field in package.json.
	if (m.packageManager === 'pnpm') {
		const builds = [...new Set(['esbuild', ...allowBuilds])].sort()
		files['pnpm-workspace.yaml'] =
			`packages:\n  - "apps/*"\n  - "packages/*"\n\n# These postinstall scripts fetch platform binaries (esbuild via vite).\n# allowBuilds is the pnpm 11+ spelling; onlyBuiltDependencies covers pnpm 10.\nallowBuilds:\n${builds.map(build => `  ${yamlKey(build)}: true`).join('\n')}\nonlyBuiltDependencies:\n${builds.map(build => `  - ${yamlKey(build)}`).join('\n')}\n`
	}

	// Yarn Berry defaults to Plug'n'Play, which breaks Vite and Module
	// Federation. Pin the node_modules linker; Yarn Classic ignores this file.
	if (m.packageManager === 'yarn') {
		files['.yarnrc.yml'] =
			`# Use the node_modules linker instead of Plug'n'Play so Vite and Module\n# Federation resolve dependencies the way they expect. Honored by Yarn 3+;\n# Yarn 1 ignores this file and already uses node_modules.\nnodeLinker: node-modules\n`
	}
	return files
}

function gitignore(m: Manifest): string {
	const base = `node_modules/\ndist/\n*.tsbuildinfo\n.DS_Store\n*.log\n`
	if (m.packageManager !== 'yarn') return base
	// Yarn Berry writes these; the allowlist keeps committed Berry assets while
	// ignoring the cache and PnP files. Harmless under Yarn Classic.
	return `${base}\n# Yarn Berry\n.yarn/*\n!.yarn/patches\n!.yarn/plugins\n!.yarn/releases\n!.yarn/sdks\n!.yarn/versions\n.pnp.*\n`
}

/** Within vite's supported range; Node 20 is EOL and pnpm 11 needs 22.13+. */
export const NODE_RANGE = '>=22.12.0'

/** YAML keys starting with a reserved indicator (like @scope) need quoting. */
export const yamlKey = (name: string): string => (name.startsWith('@') ? `"${name}"` : name)

export function workspaceScripts(m: Manifest): Record<string, string> {
	const scripts: Record<string, string> = {
		dev: 'spool dev',
		build: 'spool build',
		preview: 'spool preview',
		doctor: 'spool doctor',
		'type-check': typeCheckAll(m),
	}

	if (m.addons.includes('lint')) scripts.lint = 'eslint .'
	if (m.addons.includes('test')) scripts.test = testAll(m)

	return scripts
}

/** Run every package that has a test script, however this manager spells it. */
function testAll(m: Manifest): string {
	if (m.packageManager === 'npm') return 'npm run test --workspaces --if-present'
	if (m.packageManager === 'yarn') return 'yarn workspaces foreach -A run test'
	return 'pnpm -r test'
}

function workspacePackageJson(m: Manifest): string {
	const pkg: Record<string, unknown> = {
		name: m.name,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: workspaceScripts(m),
	}

	if (m.packageManager === 'pnpm') {
		// pnpm/action-setup and corepack read the version from here.
		pkg.packageManager = `pnpm@${PNPM_VERSION}`
	} else {
		pkg.workspaces = ['apps/*', 'packages/*']
	}

	pkg.devDependencies = sortKeys(rootDevDependencies(m))
	return json(pkg)
}

function workspaceReadme(m: Manifest): string {
	return `# ${m.name}\n\nMicro-frontend workspace scaffolded with [spool](https://github.com/bkincz/spool).\n\nAll federation wiring lives in \`spool.json\`; each app's \`vite.config.ts\` reads it\nthrough \`spool.vite.ts\` at startup, so editing the manifest is all you ever do.\n\n## Commands\n\n\`\`\`bash\n${m.packageManager} install    # install all apps\nspool dev           # run host + remotes together\nspool build         # coordinated production build\nspool preview       # serve the built apps locally\nspool deploy        # run each app's deploy command\nspool add <name>    # add a host or remote app\nspool remove <name> # remove an app and unwire it\nspool ci            # generate per-app deploy workflows\nspool upgrade       # sync generated files to the installed spool\nspool doctor        # check ports, wiring and shared deps\n\`\`\`\n\n## Deploying remotes\n\nA host resolves each remote in this order:\n\n1. \`SPOOL_REMOTE_<NAME>\` env var (ad-hoc override, e.g. point one remote at staging)\n2. the remote's \`urls\` entry for \`SPOOL_ENV\` / \`--env\` (production builds only)\n3. the remote's \`url\` in \`spool.json\` (its deployed \`mf-manifest.json\`, used in production builds)\n4. \`http://localhost:<port>/mf-manifest.json\` (local dev)\n`
}

/*
 *   RUNTIME HELPER
 ***************************************************************************************************/
/**
 * The workspace-root `spool.vite.ts`. Apps' vite configs call `spoolApp(name)`
 * from it, which reads spool.json at config load time. Dependency-free
 * (node:fs and node:path only) so it runs in any app.
 */
function spoolViteHelper(): string {
	return `/**
 * Generated by spool. Reads spool.json when Vite loads the config and derives
 * the app's dev server and Module Federation settings. Edit spool.json, not
 * this file.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export interface SpoolAppEntry {
  type: "host" | "remote";
  path: string;
  port: number;
  url?: string;
  urls?: Record<string, string>;
  remotes?: string[];
  exposes?: Record<string, string>;
}

export interface SpoolServerConfig {
  proxy?: Record<string, unknown>;
  headers?: Record<string, string>;
  host?: boolean | string;
  cors?: boolean;
}

export interface SpoolManifest {
  name: string;
  shared?: string[];
  server?: SpoolServerConfig;
  apps: Record<string, SpoolAppEntry>;
}

export interface SpoolAppConfig {
  /** Vite server/preview settings for this app. */
  server: SpoolServerConfig & { port: number; strictPort: boolean };
  /** Options for the federation() plugin from @module-federation/vite. */
  federation: {
    name: string;
    filename?: string;
    manifest?: boolean;
    remotes?: Record<string, string>;
    exposes?: Record<string, string>;
    shared: Record<string, { singleton: boolean }>;
    dts: false;
  };
}

function findManifest(from: string): string {
  let dir = resolve(from);
  for (;;) {
    const candidate = join(dir, "spool.json");
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) throw new Error("spool.vite: no spool.json found above " + from);
    dir = parent;
  }
}

/**
 * Remote lookup order: SPOOL_REMOTE_<NAME> env var, the remote's url for the
 * SPOOL_ENV environment, its default "url" (production builds only, so dev
 * keeps hitting local servers), then the local dev server.
 */
function remoteUrl(name: string, app: SpoolAppEntry, command: SpoolCommand): string {
  const envKey = "SPOOL_REMOTE_" + name.toUpperCase().replace(/-/g, "_");
  const environment = process.env.SPOOL_ENV;
  const deployed =
    command === "build"
      ? (environment !== undefined ? app.urls?.[environment] : undefined) ?? app.url
      : undefined;
  return process.env[envKey] ?? deployed ?? "http://localhost:" + app.port + "/mf-manifest.json";
}

export type SpoolCommand = "build" | "serve";

/**
 * Shared deps the app does not declare in its own package.json are dropped,
 * so apps on different frameworks never share deps they don't install.
 */
function declaredShared(dir: string, deps: string[]): string[] {
  if (!deps.length) return deps;
  let declared: Set<string>;
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    declared = new Set([
      ...Object.keys(pkg.dependencies ?? {}),
      ...Object.keys(pkg.devDependencies ?? {}),
    ]);
  } catch {
    // Sharing nothing is safe (the app just bundles its own copies); sharing
    // deps the app may not have installed is not.
    console.warn(
      "[spool] could not read " + join(dir, "package.json") + "; sharing no deps for this app. Run spool doctor."
    );
    return [];
  }
  // "@scope/pkg/subpath" is declared through its package, "@scope/pkg".
  const packageName = (dep: string): string => {
    const parts = dep.split("/");
    return dep.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0]!;
  };
  return deps.filter(dep => declared.has(packageName(dep)));
}

const ENV_REF = /\\$\\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\\}/g;

/**
 * Expands \${VAR} and \${VAR:-fallback} through the manifest server block, so a
 * proxy target can differ per machine without anyone editing a vite config.
 */
function expandEnv<T>(value: T): T {
  if (typeof value === "string") {
    return value.replace(ENV_REF, (_, name: string, fallback?: string) =>
      process.env[name] ?? fallback ?? ""
    ) as T;
  }
  if (Array.isArray(value)) return value.map(expandEnv) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, inner]) => [key, expandEnv(inner)])
    ) as T;
  }
  return value;
}

export function spoolApp(
  name: string,
  from: string = process.cwd(),
  command: SpoolCommand = "serve"
): SpoolAppConfig {
  const manifest = JSON.parse(readFileSync(findManifest(from), "utf8")) as SpoolManifest;
  const app = manifest.apps[name];
  if (!app) throw new Error('spool.vite: no app named "' + name + '" in spool.json');

  // Singleton for every share: duplicated react breaks hooks, and workspace
  // packages often carry module-level state that must resolve to one copy.
  // Non-singleton workspace shares also hit a @module-federation/vite dev bug
  // where the generated loadShare module references __mfLocalShare without
  // importing it, crashing the app at boot.
  const shared = Object.fromEntries(
    declaredShared(from, manifest.shared ?? []).map(dep => [dep, { singleton: true }])
  );
  // cors covers dev and vite preview, where hosts fetch remotes cross-origin.
  // Manifest settings come last so a workspace can override the defaults,
  // but never the port, which the app entry owns.
  const server = {
    port: app.port,
    strictPort: true,
    cors: true,
    ...expandEnv(manifest.server ?? {}),
  };

  if (app.type === "host") {
    const remotes: Record<string, string> = {};
    for (const remote of app.remotes ?? []) {
      const target = manifest.apps[remote];
      if (!target) {
        throw new Error('spool.vite: host "' + name + '" references unknown remote "' + remote + '"');
      }
      remotes[remote] = remoteUrl(remote, target, command);
    }
    // dts:false: spool types remotes via src/remotes.d.ts, so the federation
    // DTS archive is redundant and its dev-server download is flaky.
    return { server, federation: { name, remotes, shared, dts: false } };
  }

  return {
    server,
    federation: {
      name,
      filename: "remoteEntry.js",
      // Dev serves mf-manifest.json automatically; builds only emit it with
      // this flag, and hosts load remotes by their manifest URL.
      manifest: true,
      exposes: app.exposes ?? {},
      shared,
      dts: false,
    },
  };
}
`
}

/*
 *   CI WORKFLOWS
 ***************************************************************************************************/
export function ciWorkflows(m: Manifest): FileMap {
	const files: FileMap = {}
	for (const [name, app] of Object.entries(m.apps)) {
		if (!app.deploy) continue
		files[`.github/workflows/deploy-${name}.yml`] = ciWorkflow(m, name, app)
	}
	return files
}

const LOCKFILES = {
	pnpm: 'pnpm-lock.yaml',
	npm: 'package-lock.json',
	yarn: 'yarn.lock',
} as const

const INSTALL_COMMANDS = {
	pnpm: 'pnpm install --frozen-lockfile',
	npm: 'npm ci',
	yarn: 'yarn install --frozen-lockfile',
} as const

function ciWorkflow(m: Manifest, appName: string, app: AppConfig): string {
	const pm = m.packageManager
	const pnpmSetup =
		pm === 'pnpm'
			? `
            - uses: pnpm/action-setup@v6
`
			: ''

	return `# Generated by spool ci. The deploy command is copied from spool.json;
# rerun \`spool ci --force\` after changing it there.
name: Deploy ${appName}

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - 'apps/${appName}/**'
            - 'spool.json'
            - '${HELPER_FILE}'
            - 'package.json'
            - '${LOCKFILES[pm]}'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
${pnpmSetup}
            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: '${pm}'

            - name: Install
              run: ${INSTALL_COMMANDS[pm]}

            - name: Build
              working-directory: ${app.path}
              run: ${pm} run build

            # Add the secrets your deploy command needs, e.g.
            # env:
            #     CLOUDFLARE_API_TOKEN: \${{ secrets.CLOUDFLARE_API_TOKEN }}
            - name: Deploy
              working-directory: ${app.path}
              run: ${app.deploy}
`
}

/*
 *   APP FILES
 ***************************************************************************************************/
/** The expose map a fresh remote starts with; the entry differs by contract. */
export function defaultExposes(framework: Framework): Record<string, string> {
	return { './App': TEMPLATES[framework].exposeEntry }
}

export function appFiles(
	m: Manifest,
	appName: string,
	app: AppConfig,
	extras: TemplateExtras = NO_EXTRAS
): FileMap {
	const isHost = app.type === 'host'
	const refs = isHost ? remoteRefs(m, app) : []
	const files: FileMap = {
		'package.json': appPackageJson(m, appName, app, extras),
		'tsconfig.json': appTsConfig(app.framework),
		'index.html': indexHtml(appName, app.framework),
		'src/vite-env.d.ts': TEMPLATES[app.framework].viteEnv,
		...TEMPLATES[app.framework].sourceFiles(appName, isHost, refs, extras),
		...appConfigFiles(appName, app, m.addons.includes('sentry')),
	}

	if (refs.length) {
		files['src/remotes.d.ts'] = remoteTypings(refs)
	}
	if (m.addons.includes('test')) {
		files['vitest.config.ts'] = vitestConfig()
		files[ALIAS_FILE] = remoteAliasModule(m, app)
		Object.assign(files, remoteStubs(m, app))
	}
	return files
}

/**
 * The generated files `spool upgrade` refreshes on every run: the vite config
 * and, for remotes, the CORS headers static hosts need.
 */
export function appConfigFiles(appName: string, app: AppConfig, sentry = false): FileMap {
	const files: FileMap = { 'vite.config.ts': viteConfig(appName, app, sentry) }
	// Hosts fetch remote assets cross-origin in production, and static hosts
	// send no CORS headers by default. Cloudflare Pages and Netlify both read
	// this file; it is inert elsewhere.
	if (app.type === 'remote') {
		files['public/_headers'] = `/*\n  Access-Control-Allow-Origin: *\n`
	}
	return files
}

/**
 * Host files to rewrite when its remotes change. Only the ambient typings;
 * the vite config reads spool.json itself.
 */
export function hostWiringFiles(m: Manifest, host: AppConfig): FileMap {
	const files: FileMap = {}
	if (host.type !== 'host') return files
	if (host.remotes.length) files['src/remotes.d.ts'] = remoteTypings(remoteRefs(m, host))

	// The registry and the <Remote> primitive both depend on the host's remotes
	// (the primitive imports the react bridge only when one needs it), so both
	// are regenerated together whenever the remotes change.
	if (m.addons.includes('shell')) Object.assign(files, shellHostFiles(m, host))

	// Only the alias map names the remotes; vitest.config.ts stays the user’s.
	if (m.addons.includes('test')) {
		files[ALIAS_FILE] = remoteAliasModule(m, host)
		Object.assign(files, remoteStubs(m, host))
	}
	return files
}

/*
 *   FILE BUILDERS
 ***************************************************************************************************/
function appPackageJson(
	m: Manifest,
	appName: string,
	app: AppConfig,
	extras: TemplateExtras
): string {
	const { dependencies, devDependencies } = appDependencies(m, app)

	// The example button lives in the ladle ui workspace package; npm and yarn
	// link workspace packages by bare name, pnpm needs the workspace protocol.
	if (extras.uiButton && app.framework === 'react' && app.type === 'remote') {
		dependencies.ui = m.packageManager === 'pnpm' ? 'workspace:*' : '*'
	}

	return json({
		name: appName,
		version: '0.0.0',
		private: true,
		type: 'module',
		engines: { node: NODE_RANGE },
		scripts: {
			dev: 'vite',
			build: 'vite build',
			preview: 'vite preview',
			'type-check': 'tsc --noEmit',
			...(m.addons.includes('test') ? TEST_SCRIPTS : {}),
		},
		dependencies: sortKeys(dependencies),
		devDependencies: sortKeys(devDependencies),
	})
}

function sortKeys(record: Record<string, string>): Record<string, string> {
	return Object.fromEntries(Object.entries(record).sort(([a], [b]) => a.localeCompare(b)))
}

function appTsConfig(framework: Framework): string {
	// Compiler options like the JSX runtime are per app, so one framework's
	// settings never leak into another's through the shared base config. `@`
	// maps to src (matched by the vite alias) so apps import from "@/...".
	return json({
		extends: '../../tsconfig.base.json',
		compilerOptions: {
			...TEMPLATES[framework].compilerOptions,
			baseUrl: '.',
			paths: { '@/*': ['./src/*'] },
		},
		include: ['src', 'vite.config.ts'],
	})
}

function viteConfig(appName: string, app: AppConfig, sentry: boolean): string {
	const plugin = TEMPLATES[app.framework].vitePlugin
	const sentryPlugin = sentry ? sentryVitePlugin() : undefined

	const imports = [
		'import { defineConfig } from "vite";',
		'import { resolve as resolvePath } from "node:path";',
		plugin.importLine,
		'import { federation } from "@module-federation/vite";',
		...(sentryPlugin ? [sentryPlugin.importLine] : []),
		`import { spoolApp } from "${helperImport(app.path)}";`,
	].join('\n')

	const plugins = [
		`${plugin.call}`,
		'federation(app.federation)',
		...(sentryPlugin ? [sentryPlugin.entry] : []),
	]

	return `${imports}

// Generated by spool. Wiring comes from spool.json via spool.vite.ts at
// startup. Edit spool.json, not this file. The command tells the helper
// whether deployed remote urls apply (build) or local dev servers do (serve).
export default defineConfig(({ command }) => {
  const app = spoolApp(${JSON.stringify(appName)}, import.meta.dirname, command);
  return {
    server: app.server,
    preview: app.server,
    resolve: { alias: { "@": resolvePath(import.meta.dirname, "src") } },
    plugins: [${plugins.join(', ')}],
    // Module Federation needs top-level await; lock the build target.
    build: { target: "esnext", minify: false${sentry ? ', sourcemap: true' : ''} },
  };
});
`
}

function indexHtml(appName: string, framework: Framework): string {
	const entry = TEMPLATES[framework].htmlEntry
	return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="${entry}"></script>
  </body>
</html>
`
}

function remoteTypings(refs: RemoteRef[]): string {
	return refs.map(ref => TEMPLATES[ref.framework].remoteTyping(ref.name)).join('')
}
