/*
 *   IMPORTS
 ***************************************************************************************************/
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { create } from '../commands/create.js'
import { ci } from '../commands/ci.js'
import { log } from '../util/logger.js'
import { freshDir, removeDir } from './helpers.js'

/*
 *   MOCKS
 ***************************************************************************************************/
vi.mock('../util/exec.js', () => ({ run: vi.fn().mockResolvedValue(undefined) }))

/*
 *   TEST SETUP
 ***************************************************************************************************/
let dir: string
let cwd: string

beforeEach(async () => {
	dir = freshDir('spool-ci-')
	cwd = process.cwd()
	vi.spyOn(console, 'log').mockImplementation(() => {})
	await create(dir, {
		name: 'acme',
		pm: 'pnpm',
		host: 'shell',
		remotes: 'dashboard',
		install: false,
	})
	setDeploy({ shell: 'deploy-shell', dashboard: 'deploy-dashboard' })
	process.chdir(dir)
})

afterEach(() => {
	process.chdir(cwd)
	removeDir(dir)
	vi.restoreAllMocks()
})

function setDeploy(commands: Record<string, string>) {
	const manifest = JSON.parse(readFileSync(join(dir, 'spool.json'), 'utf8'))
	for (const [name, command] of Object.entries(commands)) {
		manifest.apps[name].deploy = command
	}
	writeFileSync(join(dir, 'spool.json'), JSON.stringify(manifest))
}

const workflow = (name: string) => join(dir, `.github/workflows/deploy-${name}.yml`)

/*
 *   CI
 ***************************************************************************************************/
describe('ci', () => {
	it('writes a workflow per deployable app', async () => {
		await ci({})
		expect(existsSync(workflow('shell'))).toBe(true)
		expect(existsSync(workflow('dashboard'))).toBe(true)
		expect(readFileSync(workflow('dashboard'), 'utf8')).toContain('deploy-dashboard')
	})

	it('skips existing workflows unless --force', async () => {
		await ci({})
		writeFileSync(workflow('shell'), 'user edited\n')

		const warn = vi.spyOn(log, 'warn').mockImplementation(() => {})
		await ci({})
		expect(readFileSync(workflow('shell'), 'utf8')).toBe('user edited\n')
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('--force'))

		await ci({ force: true })
		expect(readFileSync(workflow('shell'), 'utf8')).toContain('Generated by spool ci')
	})

	it('warns about apps without a deploy command', async () => {
		setDeploy({})
		const manifest = JSON.parse(readFileSync(join(dir, 'spool.json'), 'utf8'))
		delete manifest.apps.dashboard.deploy
		writeFileSync(join(dir, 'spool.json'), JSON.stringify(manifest))

		const warn = vi.spyOn(log, 'warn').mockImplementation(() => {})
		await ci({})
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('dashboard'))
		expect(existsSync(workflow('dashboard'))).toBe(false)
	})

	it('rejects when no app can be deployed', async () => {
		const manifest = JSON.parse(readFileSync(join(dir, 'spool.json'), 'utf8'))
		for (const app of Object.values(manifest.apps) as { deploy?: string }[]) {
			delete app.deploy
		}
		writeFileSync(join(dir, 'spool.json'), JSON.stringify(manifest))

		await expect(ci({})).rejects.toThrow('nothing to generate')
	})
})
