/*
 *   IMPORTS
 ***************************************************************************************************/
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { create } from '../commands/create.js'
import { upgrade } from '../commands/upgrade.js'
import { hashContent, PROVENANCE_FILE } from '../core/provenance.js'
import { log } from '../util/logger.js'
import { freshDir, removeDir } from './helpers.js'

/*
 *   MOCKS
 ***************************************************************************************************/
vi.mock('../util/exec.js', () => ({ run: vi.fn().mockResolvedValue(undefined) }))

/*
 *   TEST SETUP
 ***************************************************************************************************/
let dir: string
let cwd: string

const read = (rel: string) => readFileSync(join(dir, rel), 'utf8')
const readJson = (rel: string) => JSON.parse(read(rel))

/** Rewind the scaffold to look like an old spool version produced it. */
function ageWorkspace() {
	rmSync(join(dir, PROVENANCE_FILE))
	// Old spool versions stamped both generated files with the marker.
	writeFileSync(join(dir, 'spool.vite.ts'), '// Generated by spool. stale helper\n')
	writeFileSync(join(dir, 'apps/shell/vite.config.ts'), '// Generated by spool. stale config\n')
	rmSync(join(dir, 'apps/dashboard/public/_headers'))
	rmSync(join(dir, 'tsconfig.json'))
	rmSync(join(dir, '.prettierignore'))

	const rootPkg = readJson('package.json')
	rootPkg.engines = { node: '^20.19.0 || >=22.12.0' }
	delete rootPkg.packageManager
	delete rootPkg.devDependencies
	writeFileSync(join(dir, 'package.json'), JSON.stringify(rootPkg))

	const appPkg = readJson('apps/dashboard/package.json')
	appPkg.dependencies.react = '^18.3.1'
	appPkg.dependencies['react-dom'] = '^18.3.1'
	delete appPkg.devDependencies['@types/node']
	delete appPkg.engines
	writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(appPkg))
}

beforeEach(async () => {
	dir = freshDir('spool-upgrade-')
	cwd = process.cwd()
	vi.spyOn(console, 'log').mockImplementation(() => { })
	await create(dir, {
		name: 'acme',
		pm: 'pnpm',
		host: 'shell',
		remotes: 'dashboard',
		install: false,
	})
	process.chdir(dir)
})

afterEach(() => {
	process.chdir(cwd)
	removeDir(dir)
	vi.restoreAllMocks()
})

/*
 *   UPGRADE
 ***************************************************************************************************/
describe('upgrade', () => {
	it('regenerates the helper and vite configs', async () => {
		ageWorkspace()
		await upgrade({})

		expect(read('spool.vite.ts')).toContain('export function spoolApp')
		expect(read('apps/shell/vite.config.ts')).toContain("spoolApp('shell'")
	})

	it('adds missing files without touching existing ones', async () => {
		ageWorkspace()
		writeFileSync(join(dir, 'apps/shell/src/App.tsx'), '// my custom layout\n')
		await upgrade({})

		expect(existsSync(join(dir, 'apps/dashboard/public/_headers'))).toBe(true)
		expect(existsSync(join(dir, 'tsconfig.json'))).toBe(true)
		expect(existsSync(join(dir, '.prettierignore'))).toBe(true)
		expect(read('apps/shell/src/App.tsx')).toBe('// my custom layout\n')
	})

	it('syncs toolchain deps and adds missing ones in the right section', async () => {
		ageWorkspace()
		await upgrade({})

		const pkg = readJson('apps/dashboard/package.json')
		expect(pkg.dependencies.react).toBe('^19.2.0')
		expect(pkg.dependencies['react-dom']).toBe('^19.2.0')
		expect(pkg.devDependencies['@types/node']).toBe('^26.0.0')
		expect(pkg.engines.node).toBe('>=22.12.0')
	})

	it('updates the workspace root package.json', async () => {
		ageWorkspace()
		await upgrade({})

		const pkg = readJson('package.json')
		expect(pkg.engines.node).toBe('>=22.12.0')
		expect(pkg.packageManager).toMatch(/^pnpm@/)
		expect(pkg.devDependencies.typescript).toBeDefined()
		expect(pkg.devDependencies['@types/node']).toBeDefined()
		// Older workspaces did not carry the cli; upgrade adds it back.
		expect(pkg.devDependencies['@bkincz/spool']).toMatch(/^\^\d+\.\d+\.\d+/)
	})

	it('leaves a customized vite config alone and says so', async () => {
		const warn = vi.spyOn(log, 'warn').mockImplementation(() => { })
		writeFileSync(join(dir, 'apps/shell/vite.config.ts'), '// my hand-rolled config\n')
		await upgrade({})

		expect(read('apps/shell/vite.config.ts')).toBe('// my hand-rolled config\n')
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('has local changes'))
	})

	it('leaves a customized runtime helper alone and says so', async () => {
		const warn = vi.spyOn(log, 'warn').mockImplementation(() => { })
		writeFileSync(join(dir, 'spool.vite.ts'), '// my custom helper\n')
		await upgrade({})

		expect(read('spool.vite.ts')).toBe('// my custom helper\n')
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('has local changes'))
	})

	it('regenerates host typings', async () => {
		writeFileSync(join(dir, 'apps/shell/src/remotes.d.ts'), '// stale typings\n')
		await upgrade({})

		expect(read('apps/shell/src/remotes.d.ts')).toContain('dashboard/App')
	})

	it('writes nothing with --dry-run', async () => {
		ageWorkspace()
		await upgrade({ dryRun: true })

		expect(read('spool.vite.ts')).toBe('// Generated by spool. stale helper\n')
		expect(existsSync(join(dir, 'tsconfig.json'))).toBe(false)
		expect(readJson('apps/dashboard/package.json').dependencies.react).toBe('^18.3.1')
	})

	it('is idempotent: a fresh scaffold reports nothing to do', async () => {
		const success = vi.spyOn(log, 'success').mockImplementation(() => { })
		await upgrade({})
		expect(success).toHaveBeenCalledWith('already up to date')
	})

	it('aborts outside a workspace', async () => {
		const outside = freshDir('spool-outside-')
		process.chdir(outside)

		await expect(upgrade({})).rejects.toThrow('No spool.json')
		process.chdir(dir)
		removeDir(outside)
	})

	it('removes the unsupported rspack bundler from spool.json', async () => {
		const manifest = readJson('spool.json')
		manifest.bundler = 'rspack'
		writeFileSync(join(dir, 'spool.json'), JSON.stringify(manifest))

		await upgrade({})
		expect(readJson('spool.json').bundler).toBeUndefined()
	})

	it('adds missing root scripts without touching edited ones', async () => {
		const pkg = readJson('package.json')
		delete pkg.scripts.preview
		pkg.scripts.build = 'my custom build'
		writeFileSync(join(dir, 'package.json'), JSON.stringify(pkg))

		await upgrade({})
		expect(readJson('package.json').scripts.preview).toBe('spool preview')
		expect(readJson('package.json').scripts.build).toBe('my custom build')
	})

	it('never downgrades a dependency the workspace is ahead on', async () => {
		const pkg = readJson('apps/dashboard/package.json')
		pkg.dependencies.react = '^21.0.0'
		pkg.devDependencies.typescript = '^9.9.9'
		writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(pkg))

		await upgrade({})

		const after = readJson('apps/dashboard/package.json')
		expect(after.dependencies.react).toBe('^21.0.0')
		expect(after.devDependencies.typescript).toBe('^9.9.9')
	})

	it('writes its own ranges over a newer workspace with --pin', async () => {
		const pkg = readJson('apps/dashboard/package.json')
		pkg.dependencies.react = '^21.0.0'
		writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(pkg))

		await upgrade({ pin: true })

		expect(readJson('apps/dashboard/package.json').dependencies.react).toBe('^19.2.0')
		expect(readJson('apps/shell/package.json').dependencies.react).toBe('^19.2.0')
	})

	it('says how many ranges it left alone', async () => {
		const step = vi.spyOn(log, 'step').mockImplementation(() => { })
		const pkg = readJson('apps/dashboard/package.json')
		pkg.dependencies.react = 'workspace:*'
		writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(pkg))

		await upgrade({})

		expect(step).toHaveBeenCalledWith(
			expect.stringContaining('left 1 dependency range(s) alone')
		)
	})

	it('pulls the rest of the workspace up to the highest range in it', async () => {
		const pkg = readJson('apps/dashboard/package.json')
		pkg.dependencies.react = '^21.0.0'
		writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(pkg))

		await upgrade({})

		expect(readJson('apps/shell/package.json').dependencies.react).toBe('^21.0.0')
		expect(readJson('apps/dashboard/package.json').dependencies.react).toBe('^21.0.0')
	})

	it('aligns apps to a newer toolchain dep held at the workspace root', async () => {
		const root = readJson('package.json')
		root.devDependencies.typescript = '^9.9.9'
		writeFileSync(join(dir, 'package.json'), JSON.stringify(root))

		await upgrade({})

		expect(readJson('apps/shell/package.json').devDependencies.typescript).toBe('^9.9.9')
		expect(readJson('apps/dashboard/package.json').devDependencies.typescript).toBe('^9.9.9')
	})

	it('ignores an uncomparable range when picking the target', async () => {
		const pkg = readJson('apps/dashboard/package.json')
		pkg.dependencies.react = 'workspace:*'
		writeFileSync(join(dir, 'apps/dashboard/package.json'), JSON.stringify(pkg))

		await upgrade({})

		expect(readJson('apps/dashboard/package.json').dependencies.react).toBe('workspace:*')
		expect(readJson('apps/shell/package.json').dependencies.react).toBe('^19.2.0')
	})

	function recordAsGenerated(rel: string, content: string) {
		writeFileSync(join(dir, rel), content)
		const record = readJson(PROVENANCE_FILE)
		record.files[rel] = hashContent(content)
		writeFileSync(join(dir, PROVENANCE_FILE), JSON.stringify(record))
	}

	it('records what it generated so a later run can recognise it', async () => {
		const record = readJson(PROVENANCE_FILE)

		expect(record.files['spool.vite.ts']).toBe(hashContent(read('spool.vite.ts')))
		expect(record.files['apps/shell/vite.config.ts']).toBe(
			hashContent(read('apps/shell/vite.config.ts'))
		)
	})

	it('replaces a file it wrote even when its own output has since changed', async () => {
		recordAsGenerated('spool.vite.ts', '// an older spool wrote this\n')

		await upgrade({})

		expect(read('spool.vite.ts')).toContain('export function spoolApp')
	})

	it('leaves an edited file alone even when it still carries the marker', async () => {
		const warn = vi.spyOn(log, 'warn').mockImplementation(() => { })
		const edited = `${read('spool.vite.ts')}\n// my own helper on top\n`
		writeFileSync(join(dir, 'spool.vite.ts'), edited)

		await upgrade({})

		expect(read('spool.vite.ts')).toBe(edited)
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('has local changes'))
	})

	it('overwrites an edited file with --force', async () => {
		const edited = `${read('spool.vite.ts')}\n// my own helper on top\n`
		writeFileSync(join(dir, 'spool.vite.ts'), edited)

		await upgrade({ force: true })

		expect(read('spool.vite.ts')).not.toBe(edited)
		expect(read('spool.vite.ts')).toContain('export function spoolApp')
	})

	it('falls back to the marker when it has no record of a file', async () => {
		const warn = vi.spyOn(log, 'warn').mockImplementation(() => { })
		rmSync(join(dir, PROVENANCE_FILE))
		writeFileSync(join(dir, 'spool.vite.ts'), '// mine, no marker\n')
		writeFileSync(join(dir, 'apps/shell/vite.config.ts'), '// Generated by spool. stale\n')

		await upgrade({})

		expect(read('spool.vite.ts')).toBe('// mine, no marker\n')
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('customized'))
		expect(read('apps/shell/vite.config.ts')).toContain("spoolApp('shell'")
	})

	it('writes no provenance with --dry-run', async () => {
		const before = read(PROVENANCE_FILE)
		recordAsGenerated('spool.vite.ts', '// an older spool wrote this\n')
		const aged = read(PROVENANCE_FILE)

		await upgrade({ dryRun: true })

		expect(read(PROVENANCE_FILE)).toBe(aged)
		expect(before).not.toBe(aged)
	})
	it('skips apps whose folders are missing', async () => {
		const warn = vi.spyOn(log, 'warn').mockImplementation(() => { })
		rmSync(join(dir, 'apps/dashboard'), { recursive: true })
		await upgrade({})
		expect(warn).toHaveBeenCalledWith(expect.stringContaining('dashboard'))
	})
})
